### ISSUE TITLE
Explore programattically merging parent/child `theme.json`

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-news-2021#1]
[block-based child themes don't inherit a parent's `theme.json`](https://github.com/WordPress/gutenberg/issues/25612), which is one of the barriers to parent/child themes.

Unfortunately `class-wp-theme-json-resolver.php` doesn't have any filters, but we might be able to use `WP_Theme_JSON::merge()`, or overwrite some global until official support is implemented.

Alternatively, we could assist with https://github.com/WordPress/gutenberg/pull/27305 if we feel like it'd be worth it to start with a parent/child structure from the beginning.

**Comment by coreymckrill** [comment]
At this point I'm leaning towards not bothering with a parent/child setup and just building the News site as a standalone. Beyond the missing functionality, there are still a lot of unknowns about other site redesigns that make it hard to figure out what should go in a parent vs in the child theme. I think we can revisit this and convert this theme to a child later when we have more information and some of the missing functionality has been added.

**Comment by iandunn** [comment]
Yeah, I'm guessing that'll be best, I'd just like to try this out in case it's not as hard as we think. 

It also doesn't have to be an either/or thing. if this works, then we could create a parent that basically only contains only contains `theme.json`, and obviously shared things like header/footer templates. Everything else could still go in the child, and be migrated to the parent later on, when those features are supported (or easily hackable).

Doing it that way might save some time when we migrate, and might remind us to be thoughtful about modularity throughout the process of building the child.

**Comment by iandunn** [comment]
I dug a bit here, but it doesn't look like `WP_Theme_JSON::merge()` is useful, since we don't have access to all the places it gets assigned, in order to overwrite it. 

`block_editor_settings_all` could be used in `get_block_editor_settings()`, but there aren't any filters/globals for `wp_render_layout_support_flag()` or `wp_enqueue_global_styles`.

We could contribute to https://github.com/WordPress/gutenberg/pull/27305, but it's probably better to focus our time here instead 👍🏻

**Comment by iandunn** [comment]
https://github.com/WordPress/gutenberg/pull/34354 made it so that `theme.json` is inherited into child themes, but the values can't be overridden yet.
