### ISSUE TITLE
Visual polish of bottom banner for SotW

### ISSUE THREAD

**Issue by tellyworth** [WordPress/wporg-news-2021#100]
The bottom banner needs to be tested for SotW readiness, and any gliches raised as issues here. This is the block containing "follow the code", "find an event" etc. A recent screenshot from the test site:
<img width="1395" alt="Screen Shot 2021-12-02 at 3 41 22 pm" src="https://user-images.githubusercontent.com/7200686/144359016-d191c376-d7ff-4622-928e-f08fc2a109d9.png">

Figma for reference: https://www.figma.com/file/O9I8Jl7kaUMTX39LlRGbGO/News-Page?node-id=4659%3A8683

**Comment by danieldudzic** [comment]
The h4 headings have the `font-size` set to `30px` on the test page - Figma has them at `26px`.

**Comment by tellyworth** [comment]
Thanks @danieldudzic, well spotted. Do you have any opinions on whether #105 is the right way to fix that?

**Comment by danieldudzic** [comment]
> Thanks @danieldudzic, well spotted. Do you have any opinions on whether #105 is the right way to fix that?

Good idea - `h5` already has the correct `font-size` - let's use it.

**Comment by tellyworth** [comment]
Fixed in #105.

**Comment by tellyworth** [comment]
Any other issues here or can we close this?

**Comment by mikachan** [comment]
I've just tested this out and the only thing I can spot is the line height is slightly different between Figma and the test site. In Figma it's set to `30.4px` and on the site it's `25.6px` (from `var(--wp--custom--body--typography--line-height)`).

Otherwise, this is looking good to me, and it works well at all resolutions.

**Comment by mikachan** [comment]
I've just noticed something else! The 'Listen to all episodes' link has left padding at mobile resolution, and on Figma it doesn't. And in the same area, it looks like the headings should be a larger font size at mobile: they're `26px` on Figma, compared to `20px` on the test site. The spacing below the headings also looks like it should be increased on the test site:

| Figma      | Test site |
| ----------- | ----------- |
|  ![image](https://user-images.githubusercontent.com/1645628/144897540-aa4e1dd5-e2ed-4fa3-a5fb-fe2ae80cded9.png)    | ![image](https://user-images.githubusercontent.com/1645628/144897413-3b6d6d8f-86ee-439e-b3f8-b1929abfea53.png)       |

**Comment by mikachan** [comment]
I've opened a PR for the above issues: https://github.com/WordPress/wporg-news-2021/pull/107

**Comment by scruffian** [comment]
There is also an underline on the “Listen to all episodes” link. Do we want that too. Generally we try to underline links in content for accessibility reasons.

**Comment by tellyworth** [comment]
#116 fixes the underline for the podcast link.

**Comment by tellyworth** [comment]
Can this issue be closed now that the underline is fixed? Current screenshot from the test site:
<img width="1291" alt="Screen Shot 2021-12-09 at 3 16 26 pm" src="https://user-images.githubusercontent.com/7200686/145333521-5cff3392-0085-46bc-80ea-7733d01320ce.png">

**Comment by mikachan** [comment]
Yes, I think this issue can be closed 🎉
