### ISSUE TITLE
SotW visual polish and test for global footer

### ISSUE THREAD

**Issue by tellyworth** [WordPress/wporg-news-2021#101]
The global footer (about links etc) needs to look correct for the SotW demo. At a quick glance it seems ok, but could use some careful testing and review. Here's a recent screenshot from the test site:
<img width="1469" alt="Screen Shot 2021-12-02 at 4 06 31 pm" src="https://user-images.githubusercontent.com/7200686/144361344-9ff094f3-04eb-4234-8c10-2003fa0eb2b4.png">

What we need is:

- [ ] Check the footer on the [test site](https://wordpress.org/news-test/) against [figma](https://www.figma.com/file/O9I8Jl7kaUMTX39LlRGbGO/News-Page?node-id=4659%3A8683) for any visual problems
- [ ] Also check for responsiveness etc, across different page types
- [ ] Discuss here and open issues for anything that must be fixed for SotW and include it in the milestone.

**Comment by danieldudzic** [comment]
I have compared the test site against the Figma file and noticed:

- [x] The `font-size` for the global footer links on the test site is set to `16px`, the Figma has it set to `13px`

**Comment by tellyworth** [comment]
The font size should be fixed now, 13px as per the Figma.

Are there other issues with the footer or can we close this?

**Comment by scruffian** [comment]
This looks good to me. The only difference I can see with Figma is a few extra links. This is the figma file:
<img width="699" alt="Screenshot 2021-12-07 at 17 45 42" src="https://user-images.githubusercontent.com/275961/145080035-407d2b08-c071-4975-a92e-ef9f6d68adc6.png">

The additional links make the footer appear slightly unbalanced, should we remove them? cc @beafialho

**Comment by beafialho** [comment]
Yes, we can remove those additional links

**Comment by scruffian** [comment]
Done in https://github.com/WordPress/wporg-mu-plugins/pull/27

**Comment by ryelle** [comment]
I think this issue can be closed out now that the links are removed?

**Comment by scruffian** [comment]
The only remaining issue I see is that the bottom gap between the links and the WordPress logo is slightly off.

**Comment by mikachan** [comment]
Opened a PR for the gap between the links and the WordPress logo: https://github.com/WordPress/wporg-mu-plugins/pull/31

**Comment by scruffian** [comment]
I think this can be closed now.
