### ISSUE TITLE
Latest Release: Test site differs from mockup

### ISSUE THREAD

**Issue by ryelle** [WordPress/wporg-news-2021#114]
- The post title is longer/human friendly, while the mockup uses just the version number. The post title can be anything from "WordPress 5.8 Tatum" to "WordPress 5.8 Release Candidate 3" to "WordPress 5.8.1 Security and Maintenance Release". We could replace "WordPress", but the rest of the release name will still be in the text.
- Font is different, should it be updated if we're not changing the title? @beafialho 
- I think the space between title & date needs to be increased, it's much more obvious when hovering over the title.

| Mockup | Test site |
|--------|-----------|
| <img width="1352" alt="Screen Shot 2021-12-08 at 4 59 27 PM" src="https://user-images.githubusercontent.com/541093/145291206-5a76e1c8-e40e-4e8a-9360-bd54ea5a7f10.png"> | <img width="1308" alt="Screen Shot 2021-12-08 at 4 59 03 PM" src="https://user-images.githubusercontent.com/541093/145291155-84344b2d-4a9e-4054-96d4-ccdda028ff89.png"> |

Hovering over title
<img width="638" alt="Screen Shot 2021-12-08 at 5 05 37 PM" src="https://user-images.githubusercontent.com/541093/145292035-539e2ced-e239-4720-98fa-0ce7af343152.png">

**Comment by beafialho** [comment]
@ryelle yes, let's increase the spacing between title and date and update the font to `Inter Extra Light`. Can we remove the word WordPress from the titles? I added a mockup [here](https://www.figma.com/file/O9I8Jl7kaUMTX39LlRGbGO/News-Page?node-id=10002%3A41933) for reference.

<img width="1189" alt="Captura de ecrã 2021-12-09, às 17 39 53" src="https://user-images.githubusercontent.com/65220155/145447750-aa6e27d3-d829-4996-96c2-f54df200c015.png">
