### ISSUE TITLE
Single post: The next post link is misaligned on desktop and looks weird on mobile

### ISSUE THREAD

**Issue by matiasbenedetto** [WordPress/wporg-news-2021#117]
## Description

The next post link is misaligned on desktop:
![image](https://user-images.githubusercontent.com/1310626/145448929-4fd7b70b-d6fe-4e34-9849-79b67e208b08.png)

And it looks weird on mobile:
![image](https://user-images.githubusercontent.com/1310626/145449418-ea5fe96b-0f48-4c71-ac33-0d57840659d8.png)

**Comment by beafialho** [comment]
Thanks @matiasbenedetto. I also mentioned this issue on #122. On Mobile though, post navigation should show just "Next Post" and "Previous Post", without the post titles.
