### ISSUE TITLE
Tooling: Switch core branch to trunk

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/wporg-news-2021#12]
In 05ec95d16b4c2395d5680168785153cf4f8ff876 I switched core to the 5.8 branch because of [this](https://github.com/WordPress/gutenberg/pull/33082), which appears to have gotten fixed in the 5.8 branch, but not trunk. Presumably it will eventually be fixed in trunk as well, and then we can switch core back to trunk in this project.

**Comment by iandunn** [comment]
I think it's fixed now; I'm running `trunk` for Core and Gutenberg locally, and haven't seen any errors
