### ISSUE TITLE
Global & Local Header Improvements

### ISSUE THREAD

**Issue by beafialho** [WordPress/wporg-news-2021#120]
Here are some visual improvements.

**Desktop:**

- [x] There should be a dark overlay on the page when the categories menu is open
<img width="1413" alt="Captura de ecrã 2021-12-10, às 10 09 36" src="https://user-images.githubusercontent.com/65220155/145556843-5f093310-c6f3-48ea-989c-1baf1705c558.png">

- [x] Global header looking off in larger breakpoints ([reference on how it should look](https://www.figma.com/file/O9I8Jl7kaUMTX39LlRGbGO/News-Page?node-id=7413%3A31250))
<img width="1212" alt="Captura de ecrã 2021-12-10, às 10 09 49" src="https://user-images.githubusercontent.com/65220155/145556829-16f71839-8c03-4c8b-a183-0c5f3a1b403b.png">

- [x] Currently, there’s quite some space left in the global header menu. The rule should be: if there is enough space for all the menu links, it shouldn’t collapse into the `...` Seems like the margin is too big on the right, it can be just `25px` like in its left margin
<img width="1312" alt="Captura de ecrã 2021-12-10, às 10 12 54" src="https://user-images.githubusercontent.com/65220155/145557223-18f08865-8cf7-4980-b2b4-11f3999511b1.png">

**Mobile:**
- [x] Categories menu should be right aligned

| Test Site      | Mockup |
| ----------- | ----------- |
| <img width="343" alt="Captura de ecrã 2021-12-10, às 09 42 45" src="https://user-images.githubusercontent.com/65220155/145557515-a49ef3ab-27ba-4934-b55a-db623a876c89.png"> | <img width="252" alt="Captura de ecrã 2021-12-10, às 10 15 40" src="https://user-images.githubusercontent.com/65220155/145557633-5b7bcbb4-ff0d-42f8-a336-586b00380537.png">  |

- [x] When the Categories menu is open, the active item should be signaled and in bold.

| Test Site      | Mockup |
| ----------- | ----------- |
| <img width="409" alt="Captura de ecrã 2021-12-10, às 10 15 57" src="https://user-images.githubusercontent.com/65220155/145557793-1489bb74-bcd1-4ab4-8481-702ccc2c8a42.png">  |  <img width="252" alt="Captura de ecrã 2021-12-10, às 10 15 46" src="https://user-images.githubusercontent.com/65220155/145557898-b27e1a4a-f47c-4e44-9b53-b54d5456fcc7.png">   |

**Comment by ryelle** [comment]
@matiasbenedetto FYI I've already got other global nav changes in this PR: https://github.com/WordPress/wporg-mu-plugins/pull/32

**Comment by tellyworth** [comment]
This was merged, can we close the issue now?

**Comment by ryelle** [comment]
The global header issues should be done now. Some of the local header issues are still valid — at the very least the dark background when the menu is open; others I think had been fixed but maybe the test site wasn't up to date, so it would be good to verify.

**Comment by matiasbenedetto** [comment]
@tellyworth @ryelle I submitted a PR  with the missing overlay https://github.com/WordPress/wporg-news-2021/pull/127

**Comment by iandunn** [comment]
I checked off the boxes that are done, and opened #134 for the related issues I saw
