### ISSUE TITLE
Design regressions

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-news-2021#128]
I noticed some recent visual regressions

- [ ] https://wordpress.org/news-test/category/community/ mobile  - footer banner doesn't have edge padding anymore. still works on homepage, but not categories, search, 404, etc. maybe related to #123 
- [x] #152
- [x] #153
- [x] #154

**Comment by tellyworth** [comment]
These are now all issues so I'd prefer to close this tracking issue to make the milestone clearer. Is there a reason to keep it?

**Comment by iandunn** [comment]
Nope, that works 👍🏻
