### ISSUE TITLE
Local nav background blend, category alignment

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-news-2021#134]
Following up on #120, there are a few issues left:

- [x] #175
- [x] #176
- [ ] below `580px`, On the homepage (and probably some others), when the `Categories` dropdown is open, the local nav bottom is grey instead of transparent. see https://github.com/WordPress/wporg-news-2021/pull/127#issuecomment-994903018

**Comment by tellyworth** [comment]
I've split these issues into separate ones now. Removing this task from the milestone for clarity.

**Comment by iandunn** [comment]
Is there any reason to keep it open now that there are individual issues?

**Comment by shaunandrews** [comment]
I think this is all fixed in #178
