### ISSUE TITLE
local nav background doesn't cover past 2000px

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-news-2021#138]
once you get past `2000px`, a gap starts to appear on the left and right edges of the local nav bar

<img width="106" alt="Screen Shot 2021-12-16 at 9 03 29 AM" src="https://user-images.githubusercontent.com/484068/146416148-b7776a9c-8407-43e3-90c2-065b32ca60a0.png">

that's at `2050px`. the gap oscillates between 0px and ~10px wide as you grow/shrink the window.

related https://github.com/WordPress/wporg-news-2021/pull/90#discussion_r757643289

**Comment by shaunandrews** [comment]
In #178 I re-exported the mask to be ~2500px wide, which should be good enough for most screen resolutions.
