### ISSUE TITLE
Homepage Visual Improvements

### ISSUE THREAD

**Issue by beafialho** [WordPress/wporg-news-2021#145]
**Desktop**

- [x] #159
<img width="1433" alt="Captura de ecrã 2022-01-04, às 10 55 18" src="https://user-images.githubusercontent.com/65220155/148053652-501c730e-494d-40b1-ba15-ea7b9734c43a.png">

- [x] White bar still showing after the local nav bar
- [x] #163
<img width="1535" alt="Captura de ecrã 2022-01-04, às 10 58 03" src="https://user-images.githubusercontent.com/65220155/148052293-398a9fb1-d7b2-41cd-86e2-cb4949173acd.png">

- [x] #164
- [x] #165

<img width="1452" alt="Captura de ecrã 2022-01-04, às 11 06 23" src="https://user-images.githubusercontent.com/65220155/148052356-073ec5c5-8187-4198-b867-96c3536b7e47.png">

- [x] #166
<img width="272" alt="Captura de ecrã 2022-01-04, às 11 11 28" src="https://user-images.githubusercontent.com/65220155/148054310-a8cc6516-cab2-425d-ad22-cfb1c8da09b5.png">

- [x] #167
<img width="1455" alt="Captura de ecrã 2022-01-04, às 11 07 12" src="https://user-images.githubusercontent.com/65220155/148052485-2ed8e4cd-14ea-4452-aedf-b3bb5cbc3b35.png">

- [x] #168
<img width="1294" alt="Captura de ecrã 2022-01-04, às 11 12 50" src="https://user-images.githubusercontent.com/65220155/148052516-bc55f8b8-0f21-478f-9e03-0e49d7862d9f.png">

- [x] #169
<img width="216" alt="Captura de ecrã 2022-01-04, às 11 08 11" src="https://user-images.githubusercontent.com/65220155/148052542-d095865b-add2-42ea-8796-fac8e77e0c01.png">

It should look like this:
<img width="653" alt="Captura de ecrã 2022-01-04, às 11 32 16" src="https://user-images.githubusercontent.com/65220155/148052976-f2a3b00d-06f9-44ee-b3af-75810f9499c5.png">

- [x] #170

**Smaller screens**

- [x] #171
<img width="567" alt="Captura de ecrã 2022-01-04, às 11 30 55" src="https://user-images.githubusercontent.com/65220155/148052841-ef0f8a3a-d1d6-43ff-aff3-fe128d50731b.png">
<img width="498" alt="Captura de ecrã 2022-01-04, às 11 30 42" src="https://user-images.githubusercontent.com/65220155/148052845-1abf5401-aab8-4cba-969d-bd8d74eb26eb.png">
<img width="446" alt="Captura de ecrã 2022-01-04, às 11 30 07" src="https://user-images.githubusercontent.com/65220155/148052847-22e6546c-bcc4-4279-9c10-1a2af46a8678.png">

- [x] #172
<img width="302" alt="Captura de ecrã 2022-01-04, às 11 35 25" src="https://user-images.githubusercontent.com/65220155/148053299-a547ba32-00f2-4169-bb23-0da0a7561140.png">

- [x] #173
<img width="525" alt="Captura de ecrã 2022-01-04, às 11 36 58" src="https://user-images.githubusercontent.com/65220155/148053466-9e670e07-c58f-4043-8d52-0caa1fc1503b.png">

**Comment by iandunn** [comment]
> Same weird white background behind the local nav bar appearing in all browsers

That's covered by https://github.com/WordPress/wporg-news-2021/issues/134, so I checked off the box in this issue.

----

I think it'd be helpful to create two issues for things like this: one for critical pre-launch issues, and a second for non-critical post-launch issues.

If we get enough people, though, we'll have time to do some of the post-launch iteration before the launch.

**Comment by beafialho** [comment]
That makes sense, thanks for pointing that out. From now on I'll create issues mentioning _critical_ or _non-critical_.

Regarding this one, these two items seem non-critical for launch:
- “See All Releases” button underline should disappear on hover
- Separator lines should look full width here

**Comment by iandunn** [comment]
>  Latest release looking inaccurate on Chrome (it should be Inter Extra Light instead of EB Garamond) as it is in Safari and Firefox

Related https://github.com/WordPress/wporg-news-2021/issues/140

**Comment by tellyworth** [comment]
The heading size issue seems specific to the [test site](https://wordpress.org/news-test/). It's fine on my local install.

Could this be triggered by a Gutenberg change? Something else in the config or styles on the test site?

**Comment by iandunn** [comment]
> White bar still showing after the local nav bar

That's tracked in https://github.com/WordPress/wporg-news-2021/issues/154, so I'm checking it off here

**Comment by tellyworth** [comment]
I think these are all now tracked in separate issues. Can we either close this tracking issue, or remove it from the milestone, so we're not doubling up?

**Comment by beafialho** [comment]
Sure @tellyworth 👍
