### ISSUE TITLE
Category Pages: Security & Development

### ISSUE THREAD

**Issue by beafialho** [WordPress/wporg-news-2021#147]
- [x] Add capital letter to the top of the pages.

| Currently      | Intended |
| ----------- | ----------- |
|   <img width="1493" alt="Captura de ecrã 2022-01-04, às 16 47 19" src="https://user-images.githubusercontent.com/65220155/148093811-5b904cfd-3265-4cb0-b0ab-637435d15ec2.png"> | <img width="1009" alt="Captura de ecrã 2022-01-04, às 16 44 34" src="https://user-images.githubusercontent.com/65220155/148093683-ff3bec07-fd47-431d-b786-ea3ec8bad251.png">    |
|  <img width="1461" alt="Captura de ecrã 2022-01-04, às 16 48 06" src="https://user-images.githubusercontent.com/65220155/148094012-417bc513-bb99-4f7b-a656-2c5e5833aa5d.png">   |  <img width="1131" alt="Captura de ecrã 2022-01-04, às 16 48 19" src="https://user-images.githubusercontent.com/65220155/148093990-337801d1-fef0-4430-99bc-eb91e2ce93d3.png"> |

- [x] Page navigation should be placed in front of the stroke shape. The stroke shape should be smaller.

| Currently      | Intended |
| ----------- | ----------- |
|  <img width="1492" alt="Captura de ecrã 2022-01-04, às 16 50 06" src="https://user-images.githubusercontent.com/65220155/148094446-d279c89f-f4dc-428c-9c92-a4feaf2d7e2a.png">  |  <img width="1306" alt="Captura de ecrã 2022-01-04, às 16 50 29" src="https://user-images.githubusercontent.com/65220155/148094417-f8d8bfce-0e02-45fc-aed8-0efdc93aac77.png"> |

On mobile it should look similar as well:

<img width="351" alt="Captura de ecrã 2022-01-04, às 16 55 20" src="https://user-images.githubusercontent.com/65220155/148094973-2db5931c-cc43-4332-a901-f54c69f13e77.png">

**Comment by iandunn** [comment]
>  Add capital letter to the top of the pages.

That's tracked in #75 , and blocked by Gutenberg, so I checked it off in this issue.

**Comment by beafialho** [comment]
Got it, thanks 👍

**Comment by iandunn** [comment]
https://github.com/WordPress/wporg-news-2021/issues/78 exists too for a general pass over everything.

**Comment by MaggieCabrera** [comment]
I think this one is done via https://github.com/WordPress/wporg-news-2021/pull/208 and https://github.com/WordPress/wporg-news-2021/pull/190
