### ISSUE TITLE
Fix notices

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-news-2021#151]
- [x] `Trying to get property 'term_id' of non-object in wp-includes/class-wp-query.php:3838` on https://wordpress.org/news-test/. The stack trace includes `offset_paginated_index_posts()` and `override_category_query_args()`

**Comment by ryelle** [comment]
So far I've only seen this one notice, fixed in 45814a6. I didn't see any mention of `offset_paginated_index_posts` in the stack trace.

If there are other notices/errors, we can open other issues.
