### ISSUE TITLE
Local footer text is centered on Month in WordPress category page

### ISSUE THREAD

**Issue by tellyworth** [WordPress/wporg-news-2021#153]

**Comment by ryelle** [comment]
Fixed in https://github.com/WordPress/wporg-mu-plugins/issues/64

**Comment by ryelle** [comment]
Oh wait, this is a different issue. Screenshots for reference:

Month in WordPress category, text is centered:
<img width="1002" alt="Screen Shot 2022-01-10 at 3 27 27 PM" src="https://user-images.githubusercontent.com/541093/148834500-9edb277f-c5ea-45b6-8952-d8a71c8d9243.png">

The text should be left-aligned (home page):
<img width="993" alt="Screen Shot 2022-01-10 at 3 27 13 PM" src="https://user-images.githubusercontent.com/541093/148834501-d961a2ff-aef4-490b-9e54-f34c04784afd.png">

Note, other footer issues are handled in #157.

**Comment by allancole** [comment]
Interesting, I’ll take another look. Seems like the horizontal padding is off as well. 

![image](https://user-images.githubusercontent.com/709581/148837383-59a5ddf4-cc94-42db-8ff4-1fd17c21fedf.png)
(padding should be equal on both sides).

**Comment by ryelle** [comment]
Looks like the fix in #157 fixed this issue too, actually. I just deployed it, it should be visible on https://wordpress.org/news-test/category/month-in-wordpress/ soon.

**Comment by allancole** [comment]
Got it. I’ll grab another issue 👍

**Comment by apeatling** [comment]
Looks fixed :+1:
