### ISSUE TITLE
Mobile Improvements

### ISSUE THREAD

**Issue by beafialho** [WordPress/wporg-news-2021#156]
I tried the test site on mobile, and have addressed some inconsistencies that are critical for launch. I feel like some of the issues are duplicated but didn't want to miss any.

- [ ] #180

| Test Site | Mockup |
| --- | ----------- |
| ![IMG_8734](https://user-images.githubusercontent.com/65220155/148379159-19b1d14e-db55-4c24-bed0-8d23c2d82707.PNG) | <img width="400" alt="Captura de ecrã 2022-01-06, às 11 55 31" src="https://user-images.githubusercontent.com/65220155/148379358-d40d89e3-7001-4871-b5bd-d9e09f07af21.png"> |

- [x] #181

https://user-images.githubusercontent.com/65220155/148379532-7414aa72-35f4-4290-a255-ebda19f78d2a.MP4

https://user-images.githubusercontent.com/65220155/148379924-ed8f98b8-b748-4a4f-92f5-b2ceb48b635f.MP4

- [ ] #182

https://user-images.githubusercontent.com/65220155/148379859-25754158-766d-4f22-9335-04bb99587e2c.MP4

- [x] #183

| Test Site | Mockup |
| --- | ----------- |
|  ![IMG_8738](https://user-images.githubusercontent.com/65220155/148380568-b503d1c3-81ff-451b-84fa-c6491827b188.jpg) |  ![IMG_8745](https://user-images.githubusercontent.com/65220155/148380591-f76e4e75-c9ee-42d2-a94d-ebaf799a41fb.PNG) |

- [x] #184

| Test Site | Mockup |
| --- | ----------- |
| ![IMG_8736](https://user-images.githubusercontent.com/65220155/148380733-e5370486-a963-4b02-932b-73435d3abd78.PNG)  |  <img width="334" alt="Captura de ecrã 2022-01-06, às 12 08 18" src="https://user-images.githubusercontent.com/65220155/148380858-7984ab4f-22e7-4336-a2e0-e09e2dec8b31.png">. |

- [x] #185

| Test Site | Mockup |
| --- | ----------- |
| ![IMG_8740](https://user-images.githubusercontent.com/65220155/148381148-b75e670d-f219-47fc-8d0a-4569d2628bfb.jpg) |  <img width="467" alt="Captura de ecrã 2022-01-06, às 12 11 53" src="https://user-images.githubusercontent.com/65220155/148381281-d3ff0785-603a-4c32-aaa6-334b201e58ae.png"> |

| Test Site | Mockup |
| --- | ----------- |
|  ![IMG_8741](https://user-images.githubusercontent.com/65220155/148381424-9cb5143b-97de-4c50-ad0c-3e33db8633cf.PNG)  | <img width="365" alt="Captura de ecrã 2022-01-06, às 12 12 20" src="https://user-images.githubusercontent.com/65220155/148381399-874eb231-3bfe-4ef5-a8e0-3afe4ddf62fa.png"> |

- [x] #186

| Test Site | Mockup |
| --- | ----------- |
| ![IMG_8742](https://user-images.githubusercontent.com/65220155/148381569-5af90e97-72b7-4ee5-9ebb-22da5dec15bb.PNG) |  <img width="487" alt="Captura de ecrã 2022-01-06, às 12 15 53" src="https://user-images.githubusercontent.com/65220155/148381627-d265cb66-0ff9-4195-b0b4-ef816e67cde0.png">  |

- [x] In the Local nav bar, `News` and `Categories` should be horizontally aligned

| Test Site | Mockup |
| --- | ----------- |
| ![IMG_8743](https://user-images.githubusercontent.com/65220155/148381835-4ef6353c-00c8-435b-9d44-53d15571168f.jpg) |  <img width="512" alt="Captura de ecrã 2022-01-06, às 12 19 18" src="https://user-images.githubusercontent.com/65220155/148381993-a37dae19-d642-4f2c-a383-6d33136ff3ba.png">  |

- [x] Footer links should be left-aligned

| Test Site | Mockup |
| --- | ----------- |
|  ![IMG_8737](https://user-images.githubusercontent.com/65220155/148382129-eac7904c-b341-420a-987c-960ceec8ae76.PNG) |  <img width="476" alt="Captura de ecrã 2022-01-06, às 12 20 15" src="https://user-images.githubusercontent.com/65220155/148382159-64f7ef56-b46a-4185-bb1a-281906d69675.png">  |

cc: @kellychoffman

**Comment by iandunn** [comment]
>  In the Local nav bar, News and Categories should be horizontally aligned

https://github.com/WordPress/wporg-news-2021/issues/134

>  Footer links should be left-aligned

https://github.com/WordPress/wporg-mu-plugins/issues/44

**Comment by tellyworth** [comment]
Removing the milestone from this issue as I've split all the remaining ones out into separate issues.
