### ISSUE TITLE
Posts: Code block

### ISSUE THREAD

**Issue by beafialho** [WordPress/wporg-news-2021#161]
Code block appearance should match the [mockups](https://www.figma.com/file/O9I8Jl7kaUMTX39LlRGbGO/News-Page?node-id=4945%3A31007):

| Test Site   | Mockup |
| ----------- | ----------- |
|  <img width="1534" alt="Captura de ecrã 2022-01-07, às 11 58 10" src="https://user-images.githubusercontent.com/65220155/148541067-aff23bad-a254-400d-97a4-3077fc0a1638.png"> |   <img width="1252" alt="Captura de ecrã 2022-01-07, às 11 56 50" src="https://user-images.githubusercontent.com/65220155/148541091-b380fe23-a99e-4263-ba1c-e09cecfeea86.png">  |

**Comment by apeatling** [comment]
It seems to be using the syntax highlighter for me in posts:

<img width="707" alt="Screen Shot 2022-01-12 at 10 02 53 AM" src="https://user-images.githubusercontent.com/1464705/149196474-da51a590-db36-4a3f-9420-3105843eb549.png">

**Comment by iandunn** [comment]
[SyntaxHighlighter Evolved](https://wordpress.org/plugins/syntaxhighlighter/) is active on the site.

**Comment by apeatling** [comment]
Should be good to close this then? The color settings could be updated on the main site.

**Comment by iandunn** [comment]
🤔  I think we'll still need to add styles here, for both sites. I just mentioned the plugin because it adds a block, so I'd guess it needs to be styled _in addition to_ `core/code`. 

I updated https://wordpress.org/news-test/2021/07/29/configuring-theme-design-with-theme-json/ to have some examples of both blocks, in JS and PHP. There might be different colors for CSS and HTML as well.

We also have [Code Syntax Block](https://wordpress.org/plugins/code-syntax-block/) activated on some sites (but not  `/news`). There may be some older `/news` posts that used that, but I haven't checked. We'll eventually want styles for all 3, as we redesign other sites in the network.

I assumed we'd set colors/fonts/etc for all 3 plugins in the theme, but I haven't looked at what mechanisms they provide for that.

The mockup doesn't show syntax highlighting, but I'm guessing that's unintentional. Is that correct @beafialho ?

**Comment by beafialho** [comment]
> The mockup doesn't show syntax highlighting, but I'm guessing that's unintentional. Is that correct @beafialho ?

Yes, I've only mocked up standard rendering out of lack of knowledge here. 

It would be great if we could use [Code Syntax Block](https://wordpress.org/plugins/code-syntax-block/) for `/news` as well. It's quite close to the Figma mockup and its default color theme is dark, optimized for accessibility. What do you think of that solution?

**Comment by iandunn** [comment]
I don't have a strong preference. It might depend on how hard it is to customize the styles for SyntaxHighlighter Evolved; I'm guessing it's not hard.

We'll probably still need styles for that one regardless, since there are lots of old posts that use it.

**Comment by ryelle** [comment]
I think it would be better overall if we could standardize on Code Syntax Block across wporg, for accessibility; as mentioned the default color scheme has accessible contrast (and SyntaxHighlighter doesn't), and it's better experience for screen-reader users — currently SyntaxHighlighter Evolved blocks need to read out every line number before reading any code.

I know it would take time to go back and update past posts, so maybe SyntaxHighlighter Evolved blocks can stay as is, and old content can be updated as needed?

**Comment by iandunn** [comment]
That works for me 👍🏻

**Comment by beafialho** [comment]
> I think it would be better overall if we could standardize on Code Syntax Block across wporg, for accessibility; as mentioned the default color scheme has accessible contrast (and SyntaxHighlighter doesn't), and it's better experience for screen-reader users — currently SyntaxHighlighter Evolved blocks need to read out every line number before reading any code. 

> I know it would take time to go back and update past posts, so maybe SyntaxHighlighter Evolved blocks can stay as is, and old content can be updated as needed?


Just to make sure I understood correctly, we'll switch to use Code Syntax Block across WP.org gradually post launch?

**Comment by ryelle** [comment]
Yeah, that's what I was suggesting, we'll use Code Syntax Block for all new content.

Actually, I just tried [searching the news blog](https://wordpress.org/news/?s=wp%3Asyntaxhighlighter%2Fcode), and it looks like only that one post uses SyntaxHighlighter, so we can probably just switch it out and update that post. @iandunn did you see other posts that use it? Or did you mean on other sites like developer.w.org?

**Comment by beafialho** [comment]
> Yeah, that's what I was suggesting, we'll use Code Syntax Block for all new content.

@ryelle sounds good, thank you!

**Comment by iandunn** [comment]
That's a good point. [make/Core has 150 for instance](https://make.wordpress.org/core/wp-admin/edit.php?s=syntaxhighlighter&post_status=all&post_type=post&action=-1&m=0&cat=0&paged=1&action2=-1), but that could wait until we apply the new design there.

`wp plugin active-on-sites syntaxhighlighter` shows about 30 other sites where it's active, mostly Make and Rosetta sites.

**Comment by tellyworth** [comment]
I activated code-syntax-block on the news-test site (eventually :) ).

Here's what it looks like by default with the plugin active, on [this post](https://wordpress.org/news-test/2021/12/08/wordpress-5-9-beta-2/):

<img width="773" alt="Screen Shot 2022-01-24 at 5 22 33 pm" src="https://user-images.githubusercontent.com/7200686/150732632-46d87c15-6343-4ddb-a2e1-c88661e4c3a3.png">

**Comment by beafialho** [comment]
Thanks @tellyworth, is there a purpose in the white border?

**Comment by tellyworth** [comment]
No that was the default. I removed it in the PR #241. Haven't touched the rest of the CSS so the design might not be an exact match, but it's certainly closer.

SS attached from my local test site viewing [this post](https://wordpress.org/news/2021/03/so-you-want-to-make-block-patterns/):
<img width="780" alt="Screen Shot 2022-01-25 at 4 18 21 pm" src="https://user-images.githubusercontent.com/7200686/150915824-c0962669-735c-4b14-b09d-a7b6c22070e8.png">

**Comment by beafialho** [comment]
Thanks @tellyworth, this looks good 👍
