### ISSUE TITLE
White bar still showing after the local nav bar

### ISSUE THREAD

**Issue by tellyworth** [WordPress/wporg-news-2021#163]
it's failing to show the intended "brush" shape:
<img width="1535" alt="Captura de ecrã 2022-01-04, às 10 58 03" src="https://user-images.githubusercontent.com/65220155/148052293-398a9fb1-d7b2-41cd-86e2-cb4949173acd.png">

**Comment by ryelle** [comment]
This isn't meant to have the brush shape, the blue "categories" banner is meant to be up against the blue heading background:

<img width="1079" alt="Screen Shot 2022-01-10 at 3 47 15 PM" src="https://user-images.githubusercontent.com/541093/148837010-ea898c4b-df8f-4e3c-835f-6f823c55cd38.png">

This comes from a margin added to `site-header-offset`

**Comment by iandunn** [comment]
🤔  why was the margin added? we didn't have it before. is it something gutenberg is adding and we just need a `margin: 0`?

**Comment by ryelle** [comment]
I believe it was a gutenberg change related to the block-gap feature. `.wp-site-blocks > * + * { margin-top: var( --wp--style--block-gap ); }` is overriding the existing `site-header-offset { margin-top: 0; }`

**Comment by shaunandrews** [comment]
This is fixed in #178
