### ISSUE TITLE
Latest release looking inaccurate on Chrome (it should be `Inter Extra Light` instead of `EB Garamond`) as it is in Safari and Firefox

### ISSUE THREAD

**Issue by tellyworth** [WordPress/wporg-news-2021#164]

**Comment by ryelle** [comment]
I think this has been fixed, I see it in Inter:
<img width="1415" alt="Screen Shot 2022-01-13 at 10 10 44 AM" src="https://user-images.githubusercontent.com/541093/149356045-a4e29e96-263f-4556-9131-8c8aba70320f.png">
