### ISSUE TITLE
Latest release line height should be `110px` 

### ISSUE THREAD

**Issue by tellyworth** [WordPress/wporg-news-2021#165]
As shown [here](https://www.figma.com/file/O9I8Jl7kaUMTX39LlRGbGO/News-Page?node-id=10002%3A41933)

<img width="1452" alt="Captura de ecrã 2022-01-04, às 11 06 23" src="https://user-images.githubusercontent.com/65220155/148052356-073ec5c5-8187-4198-b867-96c3536b7e47.png">

**Comment by apeatling** [comment]
@shaunandrews @allancole Do either of you know CSS grid well? I had a look at this but it's not clear to me how to reduce the line height without affecting the other grid sections.
