### ISSUE TITLE
People's images format not squared on Chrome

### ISSUE THREAD

**Issue by tellyworth** [WordPress/wporg-news-2021#167]
<img width="1455" alt="Captura de ecrã 2022-01-04, às 11 07 12" src="https://user-images.githubusercontent.com/65220155/148052485-2ed8e4cd-14ea-4452-aedf-b3bb5cbc3b35.png">

**Comment by danieldudzic** [comment]
This seems to be displaying fine for me:

<img width="1220" alt="News_Theme_2021_Test_–_Testing_github_com_WordPress_wporg-news-2021" src="https://user-images.githubusercontent.com/905781/149260435-886a2c0c-f3f8-446b-942f-0b203417ee97.png">

**Comment by ryelle** [comment]
I also see this as squares, so I think this has been fixed.
