### ISSUE TITLE
"Subscribe" button looking off on Safari and Chrome

### ISSUE THREAD

**Issue by tellyworth** [WordPress/wporg-news-2021#169]
<img width="216" alt="Captura de ecrã 2022-01-04, às 11 08 11" src="https://user-images.githubusercontent.com/65220155/148052542-d095865b-add2-42ea-8796-fac8e77e0c01.png">

It should look like this:
<img width="653" alt="Captura de ecrã 2022-01-04, às 11 32 16" src="https://user-images.githubusercontent.com/65220155/148052976-f2a3b00d-06f9-44ee-b3af-75810f9499c5.png">

**Comment by ryelle** [comment]
The box should also have a white background on the dark footer (Month in WordPress, Releases). It also looks like the alignment is off.

news-test, Safari
<img width="529" alt="Screen Shot 2022-01-10 at 4 12 02 PM" src="https://user-images.githubusercontent.com/541093/148840112-7b8fd778-4220-4473-ab9f-f2986b0220c2.png">
<img width="496" alt="Screen Shot 2022-01-10 at 4 13 58 PM" src="https://user-images.githubusercontent.com/541093/148840397-f033f973-a9cb-4b61-b905-988ecad96af6.png">



Figma:
<img width="480" alt="Screen Shot 2022-01-10 at 4 12 31 PM" src="https://user-images.githubusercontent.com/541093/148840194-575b5276-c601-480f-9cde-01660158c9cb.png">

**Comment by apeatling** [comment]
@ryelle Where are you seeing the dark footer? I couldn't see it anywhere you mentioned.

**Comment by ryelle** [comment]
On the categories [Month in WordPress](https://wordpress.org/news-test/category/month-in-wordpress/) & [Releases](https://wordpress.org/news-test/category/releases/), or on [the 404 page](https://wordpress.org/news-test/nothinghere/).

**Comment by apeatling** [comment]
🤦 Thanks!
