### ISSUE TITLE
Same weird white background behind the local nav bar appearing in all browsers:

### ISSUE THREAD

**Issue by tellyworth** [WordPress/wporg-news-2021#171]
on smaller screens
<img width="567" alt="Captura de ecrã 2022-01-04, às 11 30 55" src="https://user-images.githubusercontent.com/65220155/148052841-ef0f8a3a-d1d6-43ff-aff3-fe128d50731b.png">
<img width="498" alt="Captura de ecrã 2022-01-04, às 11 30 42" src="https://user-images.githubusercontent.com/65220155/148052845-1abf5401-aab8-4cba-969d-bd8d74eb26eb.png">
<img width="446" alt="Captura de ecrã 2022-01-04, às 11 30 07" src="https://user-images.githubusercontent.com/65220155/148052847-22e6546c-bcc4-4279-9c10-1a2af46a8678.png">

**Comment by shaunandrews** [comment]
This is fixed in #178
