### ISSUE TITLE
In smaller screens, the local nav bar menu should be displayed vertically instead of horizontally

### ISSUE THREAD

**Issue by tellyworth** [WordPress/wporg-news-2021#172]
In smaller screens, the local nav bar menu should be displayed vertically instead of horizontally, similar to the header menu on mobile:
<img width="302" alt="Captura de ecrã 2022-01-04, às 11 35 25" src="https://user-images.githubusercontent.com/65220155/148053299-a547ba32-00f2-4169-bb23-0da0a7561140.png">

**Comment by shaunandrews** [comment]
This is fixed in #178
