### ISSUE TITLE
Separator lines should look full width here:

### ISSUE THREAD

**Issue by tellyworth** [WordPress/wporg-news-2021#173]
Separator lines should look full width here:
<img width="525" alt="Captura de ecrã 2022-01-04, às 11 36 58" src="https://user-images.githubusercontent.com/65220155/148053466-9e670e07-c58f-4043-8d52-0caa1fc1503b.png">

**Comment by shaunandrews** [comment]
I think this is fixed in #157

**Comment by apeatling** [comment]
Confirmed it's fixed
