### ISSUE TITLE
Implement design for Home page / posts index

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/wporg-news-2021#18]
- [x] add rough markup
- [x] add dynamic content
- [x] add CSS

Related #70

**Comment by iandunn** [comment]
There isn't a good way to implement the "reduced" version number in the "Latest Release" section (because of https://github.com/WordPress/gutenberg/issues/32939), so I'm just putting in the full title for now.

Once dynamic templates are available, we can add it. See #79
