### ISSUE TITLE
There are two magnifying glass icons in the `Search` field, there should only be one on the right with `29px` padding

### ISSUE THREAD

**Issue by tellyworth** [WordPress/wporg-news-2021#183]
| Test Site | Mockup |
| --- | ----------- |
|  ![IMG_8738](https://user-images.githubusercontent.com/65220155/148380568-b503d1c3-81ff-451b-84fa-c6491827b188.jpg) |  ![IMG_8745](https://user-images.githubusercontent.com/65220155/148380591-f76e4e75-c9ee-42d2-a94d-ebaf799a41fb.PNG) |

**Comment by MaggieCabrera** [comment]
Just a heads up, this isn't happening on desktop safari, chrome or FF. Could only reproduce on Safari on iOS

**Comment by iandunn** [comment]
🤔  maybe Safari IOS automatically adds a glass icon to any search field that doesn't have a submit button? They do look like different images (color, direction, etc)

**Comment by MaggieCabrera** [comment]
Solved in https://github.com/WordPress/wporg-mu-plugins/pull/79
