### ISSUE TITLE
Local nav bar looking off as we scroll

### ISSUE THREAD

**Issue by tellyworth** [WordPress/wporg-news-2021#184]
Local nav bar looking off as we scroll, it should finish with the stroke shape and have the same spacing it has on top of the menu links, between `Categories` and `All Posts`

| Test Site | Mockup |
| --- | ----------- |
| ![IMG_8736](https://user-images.githubusercontent.com/65220155/148380733-e5370486-a963-4b02-932b-73435d3abd78.PNG)  |  <img width="334" alt="Captura de ecrã 2022-01-06, às 12 08 18" src="https://user-images.githubusercontent.com/65220155/148380858-7984ab4f-22e7-4336-a2e0-e09e2dec8b31.png">. |

**Comment by shaunandrews** [comment]
Fixed in #178
