### ISSUE TITLE
Make stroke mask styles DRY

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-news-2021#205]
`wp-block-query-pagination` and `front__next-page` have duplicate `::after` styles. it'd be good to make them DRY 

xref #203

**Comment by mikachan** [comment]
Has this been addressed already? I'm struggling to find any duplicate mask styles, including with `wp-block-query-pagination` and `front__next-page`. I've had a look over any styles that are using `mask-image` or an SVG as a background image. A couple of them are similar, but I don't think they cross over enough to combine them. Or I could be looking in the wrong area?

**Comment by ryelle** [comment]
Looks like this was changed up in the refactor process (#222) so this issue can be closed. Thanks for checking, @mikachan!
