### ISSUE TITLE
Pages with short content have gap under footer

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-news-2021#223]
- [x] fix content pushed to middle in this theme - https://wordpress.org/news-test/?p=11280&preview=true

fix gap under footer in classic themes:
- [ ] https://translate.wordpress.org/projects/
- [ ] wporg-main
- [ ] check other themes

older themes do that too, so it's not a regression there, but would be nice to fix. we can push those to post-launch or try to do it before

**Comment by iandunn** [comment]
Actually, this is showing up w/ the block theme too: https://wordpress.org/news-test/?p=11280&preview=true

There was originally some CSS in the this repo or the theme which prevented that, but it may have been broken by another change.

**Comment by dd32** [comment]
I was unable to reproduce this using either of these, perhaps because It's not actually clear as to what the problem is to me.
- super short: https://wordpress.org/news-test/?p=11280&preview=true
- super long: https://wordpress.org/news-test/?p=11295&preview=true

**Comment by iandunn** [comment]
There's white space under the footer instead of the footer being stuck to the bottom:

<img width="524" alt="Screen Shot 2022-01-25 at 11 47 54 AM" src="https://user-images.githubusercontent.com/484068/151048576-16b919f0-2ff9-4e69-b996-b0ceee1c4562.png">

_( you may need to add a `border` to that `img` in dev tools to make it obvious, or open the URL and set responsive mode to a 2000px tall viewport )_

I've seen it on https://wordpress.org/news-test/?p=11280&preview=true too at some breakpoints. I think there are probably some examples like that on most sites, but fixing it will vary somewhat by the theme

**Comment by iandunn** [comment]
In the News theme, it does stick to the bottom, but the way it does has creates a side effect where the post content floats down to the middle, instead of sticking to the top: 

<img width="1354" alt="Screen Shot 2022-01-25 at 1 36 33 PM" src="https://user-images.githubusercontent.com/484068/151063796-f8f64708-583e-40b6-bce3-2226054db213.png">

**Comment by iandunn** [comment]
This fixes translate.w.org pages:

```diff
diff --git templates/style.css templates/style.css
index da61356..2840162 100644
--- templates/style.css
+++ templates/style.css
@@ -9,8 +9,11 @@
        }
 }

-body, html {
-       height: 100%;
+body {
+       /* This allows the bottom margin on `gp-content` to push the footer to the bottom of short pages. */
+       display: flex;
+       flex-direction: column;
+       min-height: calc( 100vh - var(--wp-admin--admin-bar--height) );
 }

 body,
@@ -306,7 +309,8 @@ body.wporg-make #headline h2 a:before {

 .gp-content {
        font-family: 'Open Sans', sans-serif !important;
-       margin: 20px auto;
+       margin: 20px auto auto; /* The bottom value pushes the footer to the bottom of the page on short pages. */
+       width: 100%;
        max-width: 940px;
        padding: 0 10px;
        overflow: auto;

```

...but for some odd reason setting `display: flex` on `body` breaks the layout of `table.translations tr.editor`, even though it's a grandchild element. It no longer grows to 100% width of its parent. Setting `display: table-row` fixes that, but doing that would require overriding the jQuery `hide()` call in GlotPress. An ugly hack would be setting `display: block` on _all_ the elements in the table, but it doesn't seem worth it.

I haven't found any other short pages on other sites, so I think fixing it in this theme is good enough for now.
