### ISSUE TITLE
Alignfull video hidden

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-news-2021#225]
it seems like the first `alignfull` youtube video in a post is hidden. sometimes subsequent fullscreen videos show up, but sometimes they don't. they seem to always show up in the editor. i saw this during early development, but fixed it, so this may be a regression from #207

the red dot is the hidden video that i've added a border to in dev tools to make it visible. one clue is that the dimensions are `0x0`. the video that does appear is the 2nd video in the markup.

<img width="1431" alt="Screen Shot 2022-01-22 at 7 42 38 AM" src="https://user-images.githubusercontent.com/484068/150645422-db05f3a9-b4b0-468e-a9bd-2a7914ef2ab0.png">

**Comment by ryelle** [comment]
Is there a post on news-test that demos this issue?

**Comment by iandunn** [comment]
Looks like it was fixed by #235
