### ISSUE TITLE
post navigation overflows content area

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-news-2021#227]
https://wordpress.org/news-test/2021/12/08/state-of-the-word-2021/ at 800px

might be a #207 regression

![Screen Shot 2022-01-22 at 8 19 47 AM](https://user-images.githubusercontent.com/484068/150646830-19dd1370-71e5-42ef-afe9-351f918f83a9.png)

**Comment by ryelle** [comment]
There's a `white-space: nowrap;` rule on the title that causes them to break out of the content.

This can also happen on the larger breakpoint, ex https://wordpress.org/news-test/2021/04/27/curious-about-full-site-editing/ at 1050px wide:
<img width="1188" alt="Screen Shot 2022-01-22 at 2 29 10 PM" src="https://user-images.githubusercontent.com/541093/150652914-d9f2ed34-5223-4124-8476-cb0b030257b3.png">

I'm not sure about the expected alignment, how should this wrap when it needs to? @beafialho 

<img width="1019" alt="all-top" src="https://user-images.githubusercontent.com/541093/150652867-f84285d2-d38b-41b6-9aae-5cfe5f99728d.png">
<img width="1020" alt="all-center" src="https://user-images.githubusercontent.com/541093/150652869-d3b27720-347b-44fa-9aa2-9e6be4d11316.png">

**Comment by beafialho** [comment]
@ryelle for long titles, the text should wrap middle aligned with `22px` line height.

<img width="910" alt="Captura de ecrã 2022-01-24, às 10 16 45" src="https://user-images.githubusercontent.com/65220155/150764404-3e370450-90d1-4a8c-b562-bf983f63e516.png">

Can we use end truncation if it wraps more than two lines?

<img width="907" alt="Captura de ecrã 2022-01-24, às 10 15 22" src="https://user-images.githubusercontent.com/65220155/150764232-181c56aa-16fd-42c4-978c-4e7fd9681720.png">
