### ISSUE TITLE
`.gitignore`'ing "safelist" approach is awkward

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-news-2021#23]
Right now `.gitignore` is setup to ignore everything, and then there's a few things that are explicitly tracked. 

That feels difficult to work with; e.g., to add a new file `source/wp-content/mu-plugins/main-network/site-news/podcasts.php, I have to add this to `.gitignore`:

```
!/source/wp-content/mu-plugins/
!/source/wp-content/mu-plugins/main-network/
!/source/wp-content/mu-plugins/main-network/site-news/
```

That feels unintuitive, since I have to add the folders _above_ the folder I want to allow. And then those parent folders are no longer ignored, even though I want them to be.

I think we're doing it the opposite way of how Git intends it to be done, and it'd be simpler if we used a "blocklist" approach. We could allow everything, and then ignored the plugins that aren't part of the repo.

Any thoughts?

**Comment by coreymckrill** [comment]
I don't think adding the extra lines to gitignore is that much hassle, and in this case I think it's better to exclude things by default rather than include by default. That allows for variation in our local dev setups without having to explicitly list things in the gitignore file that aren't relevant to anyone else (and also makes it harder to accidentally commit extraneous files).

**Comment by iandunn** [comment]
> allows for variation in our local dev setups

I use `.git/info/exclude` and `~/.gitignore_global` for that, and it works well for me

> makes it harder to accidentally commit extraneous files

That's a fair point. It seems pretty rare, though, so it wouldn't outweigh the devex cost IMO.

The big problem with a safelist approach IMO isn't the amount of work it takes, it's the unintuitive complexity. It's easy to add a line that _seems_ like it should work, but doesn't. I spent ~15 minutes trying to get the above example working, for example.

I don't feel too strongly, though. Worst case, we could add some comments to the start of it to document the strange behavior.

**Comment by ryelle** [comment]
I'm going to close this issue, since it seems like it isn't a big pain point, and the file already has some documentation in it about how things are included/excluded. If it's causing issues, we can reopen the issue in the future.
