### ISSUE TITLE
manual credits wrapping every username

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-news-2021#230]
eg:

https://wordpress.org/news-test/2021/12/08/wordpress-5-8-1-security-and-maintenance-release/
https://wordpress.org/news-test/2021/12/08/wordpress-5-8-2-security-and-maintenance-release/

this is not a #207 regression, posts using the actual shortcode are still fine:  

https://wordpress.org/news-test/2021/03/09/esperanza/

this one looks like post content that was copied from the script instead of using the shordcode. need to fix post content in similar way that we fixed #87 . probably just wrap them in a group block or something

putting in post-iteration since it's older content, but i don't feel strongly

**Comment by ryelle** [comment]
Looks like it's the same issue as #87, but instead of a shortcode it's a html block, so wrapping it in a group should fix it.

**Comment by StevenDufresne** [comment]
I updated the content, the pages look ok now. Shall we close this?

**Comment by ryelle** [comment]
Looks like there's a new bug with 1280px and larger:

<img width="1124" alt="Screen Shot 2022-03-28 at 11 11 46 AM" src="https://user-images.githubusercontent.com/541093/160429701-08d6a00d-3539-4142-90f9-bcb9f20a387d.png">

I think this is also missing a top-margin & max-width — maybe it needs to be wrapped in a div?

<img width="933" alt="Screen Shot 2022-03-28 at 11 13 30 AM" src="https://user-images.githubusercontent.com/541093/160430055-2603d4ec-4132-4a73-b43e-54469e149769.png">

**Comment by StevenDufresne** [comment]
It's working for me?

![](https://d.pr/vZmlpd.png)

**Comment by ryelle** [comment]
🤦🏻  I clicked the links in the issue description which take me to `/news-test` — I see the content looks correct on `/news`.

So we can close this 👍🏻
