### ISSUE TITLE
Use locally-hosted version of Inter instead of Google Fonts

### ISSUE THREAD

**Issue by beafialho** [WordPress/wporg-news-2021#234]
The Google Fonts version of Inter doesn't include italics: https://fonts.google.com/specimen/Inter

As a result, italic text will be faked by the browser by slanting the letters and that's not a good solution. Instead of sticking with this older version, we should switch to using the variable version from here, which we would bundle with the theme: https://github.com/rsms/inter/

**Comment by ryelle** [comment]
Will all the designs going forward use EB Garamond & Inter? It might make sense to set them up in an mu-plugin so anything that needs these fonts can opt in to getting the correct versions (right now they're loaded for both the theme, and the header/footer).

**Comment by beafialho** [comment]
We'll use Inter across the whole site, as a replacement of Open Sans. I'm thinking using EB Garamond for headings across the site may be the best option, but that is still open.
