### ISSUE TITLE
Use sentence case when listing categories

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/wporg-news-2021#245]
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/191598/151035285-cd6f04ec-9332-4c73-8e2e-dc7f36141447.png">

Some categories (like "heropress") aren't capitalized, so they feel out of place. We should probably enforce "Sentence case" with some CSS.

**Comment by shaunandrews** [comment]
Or maybe we need to update the "heropress" category to "HeroPress".

**Comment by ryelle** [comment]
I think it makes more sense to update the category names, that way they're correct in the archive titles too. Unless they're meant to be different?

**Comment by coreymckrill** [comment]
I went ahead and changed the `heropress` category label to `HeroPress` on the site (didn't change the slug). There weren't any other categories without sentence case, so I'll close this.
