### ISSUE TITLE
More space needed when latest release title wraps to a second line

### ISSUE THREAD

**Issue by jeffpaul** [WordPress/wporg-news-2021#252]
Not currently an issue, but if "Josephine" had been "Spurlock" (or some other letter that goes "below the line" early on in a jazzer name) then the "January 25, 2022" date would likely have been a bit hidden by that text

![Screen Shot 2022-01-28 at 11 56 26 AM](https://user-images.githubusercontent.com/2818133/151597811-3aef0f12-5c00-4660-a71c-24a9dcdd37ce.png)
.

**Comment by coreymckrill** [comment]
Looks like the spacing only gets tight like this when the post title wraps to a second line.

**Comment by beafialho** [comment]
That's right, it should have the same spacing as it does when it's not wrapped to a second line 👍 I opened up an issue that mentions it #271

**Comment by tellyworth** [comment]
Do we need both issues or can we close this one?

**Comment by beafialho** [comment]
We can close this one
