### ISSUE TITLE
Odd sideways scroll

### ISSUE THREAD

**Issue by jeffpaul** [WordPress/wporg-news-2021#253]
Mac mini (2018) running macOS Monterey (Version 12.1)
Firefox 96.0.2

I'm seeing an odd sideways scroll on my desktop view.

https://user-images.githubusercontent.com/2818133/151598139-040b7089-7815-446e-b298-456f89a9e2e2.mov

**Comment by ryelle** [comment]
Can you screenshot the "See all People" link in the "People of WordPress" section? There was a bug where the brush stroke there broke out and caused a horizontal scroll, but I thought it was fixed (see #224).

**Comment by ryelle** [comment]
From #261 
> Appears to be originating from `.front__site-title::after`

**Comment by 0aveRyan** [comment]
Sorry for the dupe!

But to follow up, appears both:
* `.front__site-title::after`
* And the Post Title Block in the Latest Release section

Both are adding some horizontal scrollbars.
![Screenshot 2022-01-28 at 14 47 16](https://user-images.githubusercontent.com/9565066/151626393-bcdb4b41-e19e-4931-9a0f-b18534bd1eff.jpg)

**Comment by jeffpaul** [comment]
Sorry I missed the initial response asking for a follow up screenshot, if that or more is still needed here please let me know.
