### ISSUE TITLE
Copy: not many folks know what `P2` is, suggestion to remove those references and allow `blog` to stand on its own

### ISSUE THREAD

**Issue by jeffpaul** [WordPress/wporg-news-2021#255]
Folks newer to WordPress and contributing likely have now context for what `P2` is so I'd suggest altering this copy to "There's a development blog..." that removes "P2" and extends the hyperlink to include "blog".

![Screen Shot 2022-01-28 at 12 06 42 PM](https://user-images.githubusercontent.com/2818133/151598959-980b82b4-018b-4518-b385-4836756bfa36.png)

**Comment by iandunn** [comment]
👍🏻

Also, I think the anchor text should include "blog", but not include "there's". Seems like better semantics. https://mrwweb.com/think-before-you-link/

**Comment by iandunn** [comment]
Updated: 

<img width="585" alt="Screen Shot 2022-01-31 at 2 25 46 PM" src="https://user-images.githubusercontent.com/484068/151883346-8e5baf4a-4040-4647-b883-8d2e58590d12.png">
