### ISSUE TITLE
Re-categorize and remove `Uncategorized` category

### ISSUE THREAD

**Issue by jeffpaul** [WordPress/wporg-news-2021#256]
I would suggest we _should_ be able to update any posts categorized with the `Uncategorized` category to something else such that we could remove that category and now have a page like this: https://wordpress.org/news/category/uncategorized/.  I might suggest `General` as the new default Category.  If this is ok, then I'm happy to go through old posts and update the `Uncategorized` labels so that this "Categories" filter view could be removed.

![Screen Shot 2022-01-28 at 12 09 46 PM](https://user-images.githubusercontent.com/2818133/151599277-2c05a454-e710-4be0-a4d8-3e814ed4c48d.png)

**Comment by coreymckrill** [comment]
This seems reasonably to me. There are currently 5 "Uncategorized" posts, so it wouldn't be too arduous to update these. I'd say go for it, @jeffpaul. I went ahead and changed the default category to "General".

**Comment by coreymckrill** [comment]
Related: #243

**Comment by dd32** [comment]
I've removed the 5 posts that were in Uncategorized, and then deleted the Category for good measure.

[Getting Started with the Figma WordPress Design Library](https://wordpress.org/news/2021/04/getting-started-with-the-figma-wordpress-design-library/)
[Become an Early Adopter With the Gutenberg Plugin](https://wordpress.org/news/2021/04/become-an-early-adopter-with-the-gutenberg-plugin/)
[Pop-Up Livestream on February 22](https://wordpress.org/news/2020/02/pop-up-livestream-on-february-22/)
Was in `Uncategorized`. Moved to `General`.

[Coloring Your Images With Duotone Filters ](https://wordpress.org/news/2021/05/coloring-your-images-with-duotone-filters/)
Was in `Features, Uncategorized`. Removed `Uncategorized`.

[Reflecting on Gutenberg’s 100th Release](https://wordpress.org/news/2021/02/reflecting-on-gutenbergs-100th-release/)
Was in `General, Releases, Uncategorized`. Removed `Uncategorized`.
