### ISSUE TITLE
Author name does not link

### ISSUE THREAD

**Issue by desrosj** [WordPress/wporg-news-2021#257]
On the current site design, author names on posts link to their WordPress.org profiles. This can be really helpful for seeing some additional context about who the person is, their role in the community, and other things they've worked on.

**Comment by ryelle** [comment]
I think this would need to be requested upstream to Gutenberg, since this uses the post-author block and I don't see an attribute to turn that into a link.

**Comment by coreymckrill** [comment]
Since we're not showing the author avatar, we might be able to switch to the `post-author-name` block instead, which does support a link. Not their wporg profile link of course, but this could be modified via the `author_link` filter.
