### ISSUE TITLE
Latest Posts section on the front page not displaying excerpts

### ISSUE THREAD

**Issue by desrosj** [WordPress/wporg-news-2021#258]
The excerpt is not present for the latest posts section on the home page. This may be intentional, but it feels broken or missing additional information. Especially since other archive areas of the blog show excerpts.

**Comment by coreymckrill** [comment]
@beafialho any thoughts on this?

**Comment by beafialho** [comment]
> Especially since other archive areas of the blog show excerpts.

That is precisely why we ended up not showing excerpts in this section. The idea for the homepage's design was to have it aggregate parts of the most visited/relevant sections of the blog, not be an archive itself as it is today. If you click "All Posts", you'll see a list of all the latest posts with excerpts, and you can always click _any_ category accessible in the top Categories bar. 

https://user-images.githubusercontent.com/65220155/151788403-b4194526-8ee6-4bc7-a975-1f0fc3adeb01.mp4

**Comment by dd32** [comment]
Just noting that the changes in #287 make the All-Posts be an actual archive with excerpts (of all posts, not just page 2 onwards), leaving the front-page to be excerpt-less.

@beafialho You added this to a milestone, but it sounds like there's no changes that need making here? Can this then be closed in favour of #287?

**Comment by beafialho** [comment]
Yes, @dd32 we can close this 👍
