### ISSUE TITLE
Top Story: Hover state cuts through dateline (which could use some negative space)

### ISSUE THREAD

**Issue by 0aveRyan** [WordPress/wporg-news-2021#260]
The top story dateline is very close to the deck and the hover state's underline cuts through it.

![Screenshot 2022-01-28 at 14 26 12](https://user-images.githubusercontent.com/9565066/151624081-bee8b39b-50bb-4ab3-80c8-232d6fe7ba05.jpg)

**Comment by coreymckrill** [comment]
Looks like the same problem as #252, not enough space between the title and the date when the title wraps to a second line. Closing this in favor of #252.
