### ISSUE TITLE
Category Archives: Very High Characters Per-Line at 1279px

### ISSUE THREAD

**Issue by 0aveRyan** [WordPress/wporg-news-2021#262]
Less blocking bug and more readability enhancement is the container on category archives allows for lots of characters per-line and exceeds the readability sweet spot between 50-75 characters.

![Screenshot 2022-01-28 at 14 55 25](https://user-images.githubusercontent.com/9565066/151627166-4578ce9b-28a9-41f5-9821-3e650c366c8e.jpg)

**Comment by iandunn** [comment]
I think this will be covered by #39 , but please reopen if there's something unique about it!
