### ISSUE TITLE
Add top and bottom margin to category archives post titles

### ISSUE THREAD

**Issue by beafialho** [WordPress/wporg-news-2021#265]
Related: #263 

Currently, post titles look too close to post meta on Desktop. Let's add a `10px` bottom margin to post titles:

**Currently:**
<img width="799" alt="Captura de ecrã 2022-01-31, às 14 26 59" src="https://user-images.githubusercontent.com/65220155/151813972-db4fb7cb-bad0-490c-9b56-83e3ef302d6a.png">

**Intended:**
<img width="801" alt="Captura de ecrã 2022-01-31, às 14 28 51" src="https://user-images.githubusercontent.com/65220155/151813992-b6ce17f2-35a0-4abd-8526-6f2d8e81ef61.png">

There's also not much spacing between each post, making the pages appear more constrained than desirable. This applies to all category archives, except the homepage "Latest Posts" section, Month in WP and Community. I tried adding a `60px` bottom margin:

**Currently:**
<img width="790" alt="Captura de ecrã 2022-01-31, às 14 53 00" src="https://user-images.githubusercontent.com/65220155/151815674-32fc4293-3188-4f33-ac7a-f86d34021533.png">

**Intended:**
<img width="788" alt="Captura de ecrã 2022-01-31, às 14 49 21" src="https://user-images.githubusercontent.com/65220155/151815325-59dbd90d-5586-44ea-9ac6-d41b298d8523.png">

I tried applying these using the browser's Inspector and believe it'll look good. However, sometimes when reviewing it doesn't look as expected.

This also applies to mobile. I added `20px` padding below each post.

<img width="366" alt="Captura de ecrã 2022-02-01, às 11 12 57" src="https://user-images.githubusercontent.com/65220155/151958720-d345f688-3d4a-411b-95ec-1019d324f494.png">

**Comment by tellyworth** [comment]
I think #279 partly fixes this, hadn't seen this issue when I started that one.
