### ISSUE TITLE
Remove duplicate `style.css` ?

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-news-2021#27]
Right now the theme has two `style.css` files:

* `wporg-news-2021/style.css` - empty except for theme meta info; has to exist for WP to recognize theme
* `wporg-news-2021/assets/style.css` - built version of `sass/` folder

Is there an advantage to having those separate? We could configure chokidar to build to `wporg-news-2021/style.css`, and only have one file. That feels more conventional to me, and would reduce a bit of clutter.

Any thoughts?

**Comment by coreymckrill** [comment]
👍 Fine with me.

**Comment by iandunn** [comment]
🤔 , although, after #26 is done, that would mean that the theme couldn't be activated until the watch/build script was run.

I guess that's ok, though, since that's part of the install process. I'll add a note to the readme too, just in case anyone is confused in the future.
