### ISSUE TITLE
Implement Events category design, posts grouped by year

### ISSUE THREAD

**Issue by beafialho** [WordPress/wporg-news-2021#281]
Is the approach taken for `Releases` (in #246) something we can apply fairly easily to `Events`? Asking because the design is identical, with the difference that numbers on the left signal the year and group posts from that year. If not, I believe the Events category page can be addressed post launch.

<img width="776" alt="Captura de ecrã 2022-02-02, às 16 22 55" src="https://user-images.githubusercontent.com/65220155/152194337-20b487b9-51fe-41e3-a037-27dbc6a39534.png">

**Comment by coreymckrill** [comment]
Just noting that this is on my radar, but I don't have a good answer yet as to whether we can fit this in. The [Initial Launch milestone](https://github.com/WordPress/wporg-news-2021/milestone/5) keeps growing almost as quickly as we close things on it 😅 . I may have a better idea after #246 is fully resolved and closed.

**Comment by beafialho** [comment]
Thank you @coreymckrill. If it's not doable by then, we can launch with the general listing appearance for this one and get the original design post launch 👍

**Comment by coreymckrill** [comment]
Ok, thanks! I think I'll move this to post-launch, but if a PR happens to come together quickly for this, we can try to squeeze it in.
