### ISSUE TITLE
Host the Google fonts we're using locally

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/wporg-news-2021#286]
As suggested [here](https://github.com/WordPress/wporg-news-2021/issues/143#issuecomment-1029802415).

Are there any reasons _not_ to do this? Thoughts, @dd32?

**Comment by ryelle** [comment]
There's already an issue for this, since the version of Inter on google fonts isn't up to date: https://github.com/WordPress/wporg-news-2021/issues/234

**Comment by coreymckrill** [comment]
Oh, perfect. Closing this as a duplicate.
