### ISSUE TITLE
All Posts: Similar spacing adjustments to other listings

### ISSUE THREAD

**Issue by beafialho** [WordPress/wporg-news-2021#296]
I remember seeing and commenting in an issue mentioning the size of the All Posts banner as is [here](https://www.figma.com/file/O9I8Jl7kaUMTX39LlRGbGO/News-Page?node-id=4852%3A33284), but I can't find it. Has that been addressed?

When I test from `trunk` I see the full list and I have a couple comments in line with others that have been addressed in other listings, regarding spacings:

- Add spacing below each post
- Add bottom padding to the post titles

| Currently | Intended |
| ------- | ------- |
|   <img width="1536" alt="Captura de ecrã 2022-02-08, às 10 02 04" src="https://user-images.githubusercontent.com/65220155/152964652-cff6f9a9-5ada-4c81-8ebf-d18058de7e5b.png">   |    <img width="1536" alt="Captura de ecrã 2022-02-08, às 10 03 28" src="https://user-images.githubusercontent.com/65220155/152964706-1f76efbd-0ef9-4c79-beb8-9ae421069fbe.png">  |

**Comment by coreymckrill** [comment]
> I remember seeing and commenting in an issue mentioning the size of the All Posts banner as is [here](https://www.figma.com/file/O9I8Jl7kaUMTX39LlRGbGO/News-Page?node-id=4852%3A33284), but I can't find it. Has that been addressed?

@beafialho is this what you're thinking of? https://github.com/WordPress/wporg-news-2021/pull/280

**Comment by beafialho** [comment]
That's right @coreymckrill!
