### ISSUE TITLE
Post Title/Post Meta disappears under submenu.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-news-2021#309]
## Issue
When viewing `/2021/05/wordpress-at-18/`, post information is hidden under the sub-menu. It looks correct on mobile but as the viewport grows larger, it gets worse. Additionally, when logged in, it's more pronounced.

|Small Viewport |Medium Viewport| Large Viewport |
|--|--|--|
| ![](https://d.pr/i/20fCXr.png) | ![](https://d.pr/i/0GXtX0.png) | ![Screensnap](https://d.pr/i/iaShTA.png) |

## Details:
Tested on: 
macOs: Monterey
Chrome: Version 97.0.4692.99 

trunk@504426cab466af1758a071f17f4ef81a87ac76b2

**Comment by StevenDufresne** [comment]
It seems like this is affecting multiple pages including `category/features/`. I wonder if there is something specific about my configuration?

**Comment by beafialho** [comment]
@StevenDufresne I also see this issue in several pages:

<img width="1535" alt="Captura de ecrã 2022-02-14, às 09 54 05" src="https://user-images.githubusercontent.com/65220155/153841309-9f5b54a8-c98e-40f0-924a-448aaba76d2e.png">

<img width="1533" alt="Captura de ecrã 2022-02-14, às 09 55 03" src="https://user-images.githubusercontent.com/65220155/153841385-fb805915-03ca-4983-a51e-99bcac14c390.png">

**Comment by ryelle** [comment]
Do you have the latest version of the header project built? Pull that, either from github or by running `composer update`, then build it with:

```
yarn workspace wporg-mu-plugins build
```

I think that should fix it.

**Comment by StevenDufresne** [comment]
I had to blow away the environment to get the changes to take. 🤔 Suspect composer must not have been pulling the updated changes. 

Anyways, working, closing.
