### ISSUE TITLE
Hover style of Subscribe button

### ISSUE THREAD

**Issue by fcoveram** [WordPress/wporg-news-2021#317]
**Section:** Subscribe to WordPress News

The subscribe button does not change when pointer is over.

<img src="https://user-images.githubusercontent.com/895819/154069700-f493bae7-4af5-452d-9db2-ab8563a87a50.gif" width="200">

**Comment by ryelle** [comment]
cc @beafialho for design input

**Comment by beafialho** [comment]
Default, hover, active and focus states for buttons are specified on Figma [here](https://www.figma.com/file/O9I8Jl7kaUMTX39LlRGbGO/News-Page?node-id=4659%3A8224).

**Comment by ryelle** [comment]
Screenshot from the figma:

<img width="890" alt="Screen Shot 2022-02-15 at 11 37 38 AM" src="https://user-images.githubusercontent.com/541093/154106962-04209182-8fb7-470e-9ce4-a1a2e74a50a5.png">

Thanks @beafialho, I totally missed it on that page.
