### ISSUE TITLE
Full-width grid of square gallery

### ISSUE THREAD

**Issue by fcoveram** [WordPress/wporg-news-2021#319]
**Page:** Community
**Breakpoint:** Desktop

The square grid gallery in the community page is not full-width as the mockup. But it does look correct on mobile.

|Front-end|Mockup|
|:---|:---|
|<img width="290" alt="CleanShot 2022-02-15 at 14 28 09@2x" src="https://user-images.githubusercontent.com/895819/154116254-b91c249a-927d-4afb-9dd4-d5da2a2d8541.png">|<img width="319" alt="CleanShot 2022-02-15 at 14 27 44@2x" src="https://user-images.githubusercontent.com/895819/154116165-31f19630-ade1-4e6d-ab31-1507661d6eb0.png">|

**Comment by beafialho** [comment]
Thank you @panchovm, as this is the same as #320, I'll go ahead and close it.
