### ISSUE TITLE
The Blue Bar

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/wporg-news-2021#32]
The Blue Bar is the "local" navigation bar that appears right below the global header. On most views it just looks like this:

![blue-bar-1](https://user-images.githubusercontent.com/916023/133348806-d46a1cbb-b9dc-43ce-823c-191ae34ae0d5.jpg)

Breadcrumb on the left, category dropdown on the right.

But sometimes it's expanded so that some or all of the breadcrumb is emphasized in a larger font:

![blue-bar-all-posts](https://user-images.githubusercontent.com/916023/133348885-9987078c-f16a-4faa-bbef-d4cd5fb89d10.jpg)

![blue-bar-podcast](https://user-images.githubusercontent.com/916023/133348895-4355dbaa-b92d-4998-93d6-0d79be5733e8.jpg)

And then, for some category archives, it's a different color:

![blue-bar-red](https://user-images.githubusercontent.com/916023/133348936-c9c178c4-7f5e-4f53-a937-3fc22f6801d4.jpg)

![blue-bar-green](https://user-images.githubusercontent.com/916023/133348940-50dd0b96-7cc5-4f2e-93ce-bb16874cb751.jpg)

![blue-bar-charcoal](https://user-images.githubusercontent.com/916023/133348948-dbd026a3-4587-425b-a1f0-a6d070f1ba61.jpg)

![blue-bar-white](https://user-images.githubusercontent.com/916023/133348952-1339ffaf-e783-4938-bd6c-9c3598eba040.jpg)

The consistent things are:

* Breadcrumb
* Category dropdown
* The paint stroke on the bottom edge (should be able to make this an SVG and modify its color with CSS)

Does it make sense to try and build this bar as a template part, and contain the logic for the variations within it? Or would it be better to construct the bar in each page-level template separately? (i.e. single.html, page.html, archive.html, etc. all have their own markup for the bar)

**Comment by coreymckrill** [comment]
On the views that have an expanded bar, like the two examples above, the expanded part could potentially be decoupled from the standard part of the blue bar. That way, we could standardize most of it in a template part and then just add the specialized parts to the page-level templates...

**Comment by iandunn** [comment]
> decoupled from the standard part

That sounds like a great idea!
