### ISSUE TITLE
Community posts grid should be full-width

### ISSUE THREAD

**Issue by beafialho** [WordPress/wporg-news-2021#320]
I missed this detail earlier but currently, the Community category page isn't full width according to the mockups. The post grid should also sit below the Local Nav Bar, instead of after it.

| Now | Intended |
| ----- | ----- |
|  <img width="1533" alt="Captura de ecrã 2022-02-15, às 17 32 35" src="https://user-images.githubusercontent.com/65220155/154117084-cc9d6809-3841-4772-b3ca-e2f67157f5e4.png"> |  <img width="1203" alt="Captura de ecrã 2022-02-15, às 17 32 16" src="https://user-images.githubusercontent.com/65220155/154117105-97d4f321-300d-4ee4-bc5c-0b168056eea6.png">  |

**Comment by ryelle** [comment]
It's full-width now, but still has a visible cutoff under the local nav. In the design, the local nav overlaps the first row of people a little.

<img width="1568" alt="Screen Shot 2022-02-17 at 11 39 42 AM" src="https://user-images.githubusercontent.com/541093/154528137-b638b08e-f493-4811-8f27-6055691fcd20.png">
