### ISSUE TITLE
Players not showing up in Podcast

### ISSUE THREAD

**Issue by beafialho** [WordPress/wporg-news-2021#331]
In the Podcast category archive no players are showing up as they did in the preview. In the posts, the player showing up isn't the correct one, it's a black default player instead.

<img width="1480" alt="Captura de ecrã 2022-02-17, às 09 05 31" src="https://user-images.githubusercontent.com/65220155/154443654-d8391cee-20f8-44e4-af4f-264e0aded817.png">

<img width="571" alt="Captura de ecrã 2022-02-17, às 09 05 49" src="https://user-images.githubusercontent.com/65220155/154443667-fd4f2b7d-d562-4ce8-9247-5e98ca354ab8.png">

Mockups can be found [here](https://www.figma.com/file/O9I8Jl7kaUMTX39LlRGbGO/News-Page?node-id=11963%3A46999). And mockups for other screen sizes [here](https://www.figma.com/file/O9I8Jl7kaUMTX39LlRGbGO/News-Page?node-id=11359%3A107966).

<img width="1282" alt="Captura de ecrã 2022-02-17, às 09 13 48" src="https://user-images.githubusercontent.com/65220155/154443568-ac1962fe-f81a-4632-94fa-1764d0515b19.png">

<img width="1013" alt="Captura de ecrã 2022-02-17, às 09 13 59" src="https://user-images.githubusercontent.com/65220155/154443561-55d2a1d9-cd14-4a87-a2d6-de538152171e.png">

**Comment by iandunn** [comment]
IIRC this was working in https://github.com/WordPress/wporg-news-2021/pull/210, so it may be a matter of configuring the plugin on production to match how it was configured in the local env, or something along those lines.

**Comment by ryelle** [comment]
It looks like the plugin was pinned to a specific version, so the version on News is a few behind the one in the dev env. I've updated it to the latest version, and it's showing the players correctly now 👍🏻
