### ISSUE TITLE
Community Grid: Posts with images have double links

### ISSUE THREAD

**Issue by ryelle** [WordPress/wporg-news-2021#340]
On https://wordpress.org/news/category/community/, posts with featured images have links to the post on both the title and the image. The image's link text (for screen readers) uses the alt, which is usually filled out but sometimes empty, which is a bad experience. Having two links to the same destination is also redundant. For keyboard users, it means you need to tab twice as much to get through the page — once for the image, once for the title.

Unfortunately, we can't just remove the image's link without also loosing some hover/click-area, the title link only wraps the title:

<img width="351" alt="Screen Shot 2022-02-18 at 11 46 13 AM" src="https://user-images.githubusercontent.com/541093/154725930-a6ca4065-5c2b-42aa-984b-1f8ddb934033.png">

**Comment by coreymckrill** [comment]
@ryelle I actually think just removing the link from the featured image might be the best solution here. It does reduce the _clickable_ area a bit (though the `entry-meta` container already blocked part of the image's clickable area), but the hover effects still work for the whole post grid item--all while eliminating the extra tab for keyboard navigators. Seems like a reasonable improvement.

Demo: https://d.pr/v/mqRe8i
