### ISSUE TITLE
Implement design for the Code block

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/wporg-news-2021#351]
| Content width | Mobile |
| --- | --- |
| ![code-block-content-width](https://user-images.githubusercontent.com/916023/155407964-69d8676a-0b45-4f9f-9ca5-00930ab13912.jpg) | ![code-block-mobile](https://user-images.githubusercontent.com/916023/155407978-e974a2cd-984c-42ec-8ef3-6f6b1c96a166.jpg) |

https://www.figma.com/file/O9I8Jl7kaUMTX39LlRGbGO/News-Page?node-id=4659%3A11582

Refs #9

**Comment by ryelle** [comment]
FYI: https://github.com/WordPress/wporg-news-2021/issues/161 — I think the code-syntax-block plugin needs to be activated and maybe the content updated.

**Comment by coreymckrill** [comment]
Ah thanks. Looks like this is actually done then, although in [this post](https://wordpress.org/news/2021/03/so-you-want-to-make-block-patterns/) the code block isn't styled correctly. It might just not be using the right code block...

**Comment by coreymckrill** [comment]
Turns out we just needed to activate the Code Syntax Block plugin on the News site. I guess before it was only activated on `news-test`.
