### ISSUE TITLE
Gutenberg: Missing icons for the WP Briefing callout

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/wporg-news-2021#36]
The design calls for a row of icons representing the different services where you can listen to the WP Briefing podcast. At present, the Social Icons block only supports Spotify and RSS, so the following services only get a generic link icon:

- [ ] Apple Podcasts
- [ ] Pocket Casts
- [ ] Stitcher

We should either add some custom SVGs for those icons or submit a PR to Gutenberg to get those icons added.

**Comment by tellyworth** [comment]
@kellychoffman @beafialho can Design help with this?

**Comment by beafialho** [comment]
Maybe these would be useful for users in Gutenberg as well, but I'm fine with whatever you think works best.

Here are the SVG files: [podcast_icons.zip](https://github.com/WordPress/wporg-news-2021/files/7416464/podcast_icons.zip)

**Comment by iandunn** [comment]
I overwrote the "chain" icon in 616100d, as a workaround until Gutenberg adds them.

Moving to the post-launch iteration milestone so that they can be removed once they're no longer needed.

**Comment by iandunn** [comment]
xref https://github.com/WordPress/gutenberg/issues/36755

**Comment by iandunn** [comment]
I opened #131 for the remaining work
