### ISSUE TITLE
Ellipses from CSS looks unnecessary on post excerpt

### ISSUE THREAD

**Issue by vijayhardaha** [WordPress/wporg-news-2021#366]
https://github.com/WordPress/wporg-news-2021/blob/358e279c4247075f426e1186226fe189162b1550/source/wp-content/themes/wporg-news-2021/sass/blocks/_post-excerpt.scss#L1-L4

https://wordpress.org/news/category/interviews/
https://wordpress.org/news/category/releases/page/2/

![Screenshot 2022-03-18 at 11 55 04 AM](https://user-images.githubusercontent.com/25227317/158950024-21d46011-26d2-425b-a7b2-ecbc3a8ac54d.png)
![Screenshot 2022-03-18 at 12 05 26 PM](https://user-images.githubusercontent.com/25227317/158950036-07155e56-0338-4904-8854-044a0aea4fd2.png)

**Comment by StevenDufresne** [comment]
This was introduced in #31 

@coreymckrill It isn't clear looking through the PR why the ellipses are necessary since they are already truncated. Thoughts?

**Comment by coreymckrill** [comment]
🤔 That's odd. I'm guessing that something about the way the excerpt block was implemented by the theme changed later. Or something about the way they are implemented in Gutenberg changed. Either way, seems safe now to assume we can remove the CSS rule.
