### ISSUE TITLE
News Page Subscribe to Wordpress News Top border Full width issue

### ISSUE THREAD

**Issue by varshil-doshi** [WordPress/wporg-news-2021#379]
Hello,
In Responsive (781px and below) the **Subscribe to WordPress News Section** in **News Page** is not coming full width and due to which the top border is not coming full width.

**URL:** https://wordpress.org/news/

For Better understanding, please find screenshots.

![CleanShot 2022-06-08 at 17 52 12](https://user-images.githubusercontent.com/94299018/172821351-38348ea2-d074-4ae9-9ca8-96ef3e3670d9.png)

Thank you.

**Comment by ryelle** [comment]
This was fixed in https://github.com/WordPress/wporg-news-2021/commit/b4489a621ffb07e31fa364c92741d96644a8af95.
