### ISSUE TITLE
Implement design for Releases category

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/wporg-news-2021#38]
![releases](https://user-images.githubusercontent.com/916023/135541557-4d4f641b-04c4-4f19-886f-45f0cfa26472.jpg)

* [Design](https://www.figma.com/file/O9I8Jl7kaUMTX39LlRGbGO/News-Page?node-id=4852%3A36290)
* [Interactions](https://video.wordpress.com/v/Da55hR9D)

I'm not sure this one will be possible using block templates. The majority of the posts in this category don't have any meta data (taxonomy term, etc.) to identify which version it relates to; just the version number as part of the post title. So we'll either need to add a taxonomy or post meta value for the version, or write some regex to try and scrape it from the post title. Either way, we'll probably need a PHP template in order to output the markup accurately.

And then there are a few posts that aren't actually about a WP release (like [this one](https://wordpress.org/news/2021/02/reflecting-on-gutenbergs-100th-release/)). Not sure how to present those...

- [x] rough markup #51
- [x] final markup and CSS

**Comment by iandunn** [comment]
🤔 

I'm generally leery of using regex -- _("...now you have two problems")_ -- but I also think it'd be impractical to retroactively apply terms for a new taxonomy, and also impractical to expect authors to use the taxonomy in the future.

I wonder if a really simple regex like `\d(\.\d)+` would be good enough?

https://regex101.com/r/iKnTvJ/1

If that doesn't match anything, then a second regex could search for `{number}{ordinal}` ( _psuedoregex_ 😉 )

...and if that fails, then maybe we leave the space blank? It's probably not worth the time/tech debt to get the last 5% of them.

**Comment by iandunn** [comment]
That regex could be used to retroactively apply a taxonomy term, but we'd still have the problem of folks having to know that they need to use it.

**Comment by iandunn** [comment]
Another idea would be to add that "version number" area part of post content, so it's obvious to folks that they need to add it? Placeholder text could give instructions. 

But then it'd have to be hidden on the single post view. Maybe we could add it in the editor as an inline panel, so that the editor would appear more like the category view. but instead of saving to `post_content`, it'd  save as a taxonomy term. That seems like way too much trouble for something like this, though.

**Comment by coreymckrill** [comment]
Here's a slightly more complex expression `(\d{0,3}(\.\d{1,3})+)` that gets all but 12 of the post titles in the archive:

https://regex101.com/r/NgC94E/1

For those 12, most of which are the oldest posts, we could probably just leave it blank.

**Comment by iandunn** [comment]
That looks good 👍🏻

**Comment by iandunn** [comment]
I don't think there's a good way to implement the version number stuff right now; it'd be better to do that in #75 once dynamic templates are available.

The rest of the design can still be implemented in this issue though.
