### ISSUE TITLE
News page: reducing the height of the intro section

### ISSUE THREAD

**Issue by aatanasovdev** [WordPress/wporg-news-2021#391]
## Description

On small desktop devices such as MacBooks, the intro area of [the News page](https://wordpress.org/news/) looks like this:

<img width="1435" alt="news" src="https://user-images.githubusercontent.com/38669058/191075960-5aebf8db-f953-4500-a2dd-87b877ca195e.png">

The issue is that no content is visible above the fold. 

The intro area is prepared similar to [the initial Figma design](https://www.figma.com/file/O9I8Jl7kaUMTX39LlRGbGO/News-Page?node-id=4852%3A27016). However, previewing the Figma design, most of the Latest Release section is visible on small desktop devices, which isn't the case in the coded version.

Also, the `Log In / Register` top bar wasn't considered in the design, which further lowers the content.

## Proposed solution

Reducing the top and bottom spacing similar to this mockup:

<img width="1435" alt="intro-reduced" src="https://user-images.githubusercontent.com/38669058/191077233-56f7746e-efbc-4a16-af75-ddfeb9cdae2d.png">

This solution tends to improve the user experience. Reducing the unnecessary top and bottom spacing will help users find the content quickly.

Please let me know what you think.

**Comment by StevenDufresne** [comment]
I agree. I think we can remove the margin and it will still follow the grid.

**Comment by ryelle** [comment]
This was also reported at #394, and fixed in #413.
