### ISSUE TITLE
Text is hidden in the responsive and there is no consistency.

### ISSUE THREAD

**Issue by Himshekhar07** [WordPress/wporg-news-2021#399]
The text on this page [https://wordpress.org/news/category/releases/](https://wordpress.org/news/category/releases/) is page is not consistent and also hidden in the responsive design.
Additionally, the text should be consistently displayed in the same location on the page, regardless of screen size or the device used to access the page. This helps to ensure that users can easily locate and understand the date information.

I am attaching the video and screenshot with the solution:
[https://share.cleanshot.com/P70LR4lXG18CGRT8v1L6](https://share.cleanshot.com/P70LR4lXG18CGRT8v1L6)
[https://share.cleanshot.com/NN7F489VJTkDnDJx7MgD](https://share.cleanshot.com/NN7F489VJTkDnDJx7MgD)

Adding the following CSS will solve this issue:

`@media screen and (max-width:768px) { 
     body.category-releases .wp-block-post .wp-block-wporg-release-version {
          bottom: 0;
     }
 }`

**Comment by iandunn** [comment]
I think this can be addressed in #398, since it's basically the same issue.
