### ISSUE TITLE
Prevent orphans in content

### ISSUE THREAD

**Issue by eidolonnight** [WordPress/wporg-news-2021#406]
[Orphans](https://en.wikipedia.org/wiki/Widows_and_orphans), lone words at the ends of blocks of text, are commonplace across the freshly redesigned parts of WordPress.org. In various [News](https://wordpress.org/news/) posts, orphans appear in both titles and body content for common breakpoints.

![CleanShot 2023-07-27 at 09 39 36@2x](https://github.com/WordPress/wporg-parent-2021/assets/115154/a674b186-9a67-41ce-a5ac-0e7814ee5fc4)

![CleanShot 2023-07-27 at 09 41 23@2x](https://github.com/WordPress/wporg-parent-2021/assets/115154/00a3236d-75e4-44d4-b990-323b7cf8a807)

While orphans can sometimes be addressed with the manual addition of a non-breaking space, that is not possible in post titles, and trying to manually adjust body text is an exercise in futility due to the variety of screen/window sizes, contributors, etc. I'd like to propose that this be addressed within the theme.

@adamwoodnz [implemented a fix for WP20.WordPress.net](https://github.com/WordPress/wp20.wordpress.net/blob/trunk/wp-content/themes/twentyseventeen-wp20/functions.php#L41), which could be used here. There are also javascript options for this.

**Comment by adamwoodnz** [comment]
Transferred to the News theme repo, as I realised News does not use the parent theme. We can duplicate the solution there.

**Comment by adamwoodnz** [comment]
[PR](https://github.com/WordPress/wporg-parent-2021/pull/119) is in progress for the Parent theme, which we can replicate in News if effective.
