### ISSUE TITLE
Subscribe Popup text are not visible properly

### ISSUE THREAD

**Issue by dd32** [WordPress/wporg-news-2021#417]
As reported in https://meta.trac.wordpress.org/ticket/7474 by @pitamdey

URL : https://wordpress.org/news/podcast/
When we click subscribe, the popup appears in that the text is not visible properly.
I have attached the screenshot for a better understanding

<img width="1436" alt="Screenshot 2024-02-16 at 10 46 14 AM" src="https://github.com/WordPress/wporg-news-2021/assets/767313/37ecd115-9bb8-4c69-b5ae-d3a1e713e019">

**Comment by ryelle** [comment]
Fixed by #418
