### ISSUE TITLE
`post-meta` vs `entry-meta`

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-news-2021#45]
`post/_meta.scss` uses the `post-meta` class, but all the templates use `entry-meta`, so none of those rules are applying. I'm guessing that's an artifact from the Blockbase fork.

We should probably either rename them to be consistent, or remove the dead code and corresponding SVGs.

**Comment by coreymckrill** [comment]
Yeah, I think that's an artifact.

Maybe we should rename the `post` directory to `components` or something so it's a bit more accurate and versatile...
