### ISSUE TITLE
Show post footer archive regardless of device?

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-news-2021#46]
Right now the post footer archive is hidden from mobile devices; it's only shown to tablets and desktops. It contains the "Follow the Code", "Find an Event Near You", etc info.

https://github.com/WordPress/wporg-news-2021/blob/8dad00ccfe144ddb3ee37c84f044188da47dd0b0/source/wp-content/themes/wporg-news-2021/sass/post/_footer.scss#L2

Was that done to avoid the user having to scroll too much to reach the footer?

It seems philosophically "wrong" to hide content from someone based on their device. Another solution could be to use art 
direction to show the content in a way that's appropriate for mobile devices.

For example, maybe it'd be an "accordion" on mobile devices, and users would tap on the heading to display the excerpt/icons/etc.

**Comment by beafialho** [comment]
Could you add a screenshot of the info you're referring to?

**Comment by iandunn** [comment]
It's the area above the footer that has "Follow The Code", "Find An Event Near You", etc

**Comment by beafialho** [comment]
Ah, I see!

The area with this info shouldn't appear on posts, only on the homepage and category pages, regardless of device. If you check out the "Pages" layer in [the Figma file](https://www.figma.com/file/O9I8Jl7kaUMTX39LlRGbGO/?node-id=4659%3A8683), you'll see these mocked up for both desktop and mobile.

**Post**
<img width="717" alt="Captura de ecrã 2021-10-22, às 15 52 19" src="https://user-images.githubusercontent.com/65220155/138476324-4dc8a266-c166-47ec-ae33-8459258be054.png">

**Page**
<img width="543" alt="Captura de ecrã 2021-10-22, às 15 53 17" src="https://user-images.githubusercontent.com/65220155/138476353-c7111448-8d15-4d1a-9f07-81d79ab42f42.png">

**Comment by iandunn** [comment]
Ah, thanks! @coreymckrill , was there a technical limitation or something that led to the `display: none`?

**Comment by coreymckrill** [comment]
In the mockup I was using, it didn't show the footer on the mobile view, but it looks like that has now been updated and the footer boxes are shown.
