### ISSUE TITLE
Delete blank template?

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-news-2021#48]
Are we using the `blank.html` template, or is an artifact of blockbase?

if it's the latter, it'd be nice to remove it, to avoid distracting clutter

**Comment by coreymckrill** [comment]
I'm pretty sure that's a BlockBase artifact. I support deleting it 👍

**Comment by iandunn** [comment]
👍🏻 , deleted

**Comment by iandunn** [comment]
does the same apply to `header-footer-only`?

**Comment by coreymckrill** [comment]
Yep, looks like it.
