### ISSUE TITLE
Create Git -> SVN sync script for deploys

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-news-2021#5]
WordCamp's one is probably a good to fork. Ideally, it could go in https://github.com/WordPress/wporg-repo-tools and be reused by all themes and plugins.

We'll also need to create a w.org/news-test site as part of this.

**Comment by iandunn** [comment]
Here's my thoughts on this:

* make it a generic script in `repo-tools`. News' ~~`package.json`~~ `composer.json` would have a `sync-svn` command to call it w/ the necessary params
* use PHP instead of BASH, incorporate a lot of the stuff from WordCamp's sync script
* it'd have to be run locally, because `yarn` etc aren't available on w.org sandboxes. that means committers will have to have an active SSH tunnel to the SVN server.
* the script loops through each plugin/theme
    *  checks out/updates the corresponding SVN version, and builds all the workspaces. 
    * show `svn stat` to the dev
* prompt for confirmation & commit

it wouldn't handle mu-plugins, since they don't map cleanly to the SVN repo. for News we'd likely want `mu-plugins/main-network/site-news.php`, rather than multiple individual files. Maybe it's fine to just manually sync that if we ever have it? Open to ideas

Any thoughts before I start? @coreymckrill , @ryelle , @dd32

**Comment by dd32** [comment]
> it'd have to be run locally, because yarn etc aren't available on w.org sandboxes. that means committers will have to have an active SSH tunnel to the SVN server.

I don't think that's a good assumption to make, while I know some do it that way, it seems like a less than ideal scenario.

I personally do have `yarn` installed on my sandbox, stored in `~/public_html/bin` (Which doesn't normally exist, but is in `$PATH`) along with a lot of the other tools that we use every day.  I think we'd be better off having systems involvement to add the proper paths and/or toolings to sandboxes that are being used for modern development on dotorg.

**Comment by iandunn** [comment]
Yeah, I've got some custom stuff installed too, but I didn't want to make everyone do that.

I don't think involving Systems is a good idea, since there's a 50% chance it'll be months before they have time to get to it.

Are there tangible benefits to running it on the sandbox instead of locally?

**Comment by iandunn** [comment]
IMO the ideal form of this is<sup>[1]</sup>:

1. We merge to the `trunk` branch
1. GH runs a webhook which notifies w.org of the new commits
2. w.org runs a script (built/maintained by systems) that:
    a. runs `yarn workspaces build` (which we maintain, so we can update it when new tasks are needed)
    b. runs `svn commit -m 'Sync with Git {HEAD}'`
5. we manually deploy

If we're gonna ask Systems for something, I'd rather it be that. They're already doing it within a8c, so there's a good chance they have stuff they can reuse.

----

[1]: Well, really the ideal is we remove SVN from the pipeline entirely, but that doesn't seem realistic right now. I'd be happy to be wrong about that, though.

**Comment by coreymckrill** [comment]
I was envisioning this being more like the one we have for WordCamp, which runs locally:

1. Merge a PR on GitHub
2. Check out trunk locally and pull the changes (The relevant svn directories are checked out on top of the relevant git directories, or in a deploy directory as discussed elsewhere)
3. Run the sync script, which will
  * Do a `yarn workspaces build`
  * List the git commits that have happened since the last sync
  * Run `svn commit -m 'Sync with Git {HEAD}'`
4. Deploy manually, after checking that the sync commit contains only the intended changes

Yes, committers would have to have an active SSH tunnel to the SVN server. But that seems like less of a hassle than depending on Systems.

**Comment by iandunn** [comment]
I've made some progress here, but want to do a few manual syncs before working on the script more, to get a good workflow down.

I'm gonna focus more on other tickets for a bit, while making notes and tweaks here.

**Comment by iandunn** [comment]
the learn script might also be useful here:

https://github.com/WordPress/learn/pull/311/files

**Comment by iandunn** [comment]
Added in `r18644-dotorg`. You can run it [similar to the other ones there](https://github.com/WordPress/learn/pull/311#issuecomment-1076004058). Kudos @dd32 for adding those!

As an extra convenience, I also setup [a local `sync` command](https://github.com/iandunn/dotfiles/commit/01d5f33b0d032e06be10034b1294d3fa65ddb5e7) if that's useful to anyone.

cc @ryelle  @coreymckrill @StevenDufresne @tellyworth
