### ISSUE TITLE
Post titles not shown until hover

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-news-2021#50]
Some screens in the mockup have post titles being hidden until the user hovers over them. 

That felt like [mystery meat navigation](https://en.wikipedia.org/wiki/Mystery_meat_navigation) to me, so I did some reading about it. Here's some informative discussions I came across:

* https://ux.stackexchange.com/questions/101703/is-it-bad-practice-to-hide-content-expecting-some-user-interaction-to-show-it
* https://ux.stackexchange.com/questions/33960/are-hover-states-necessary
* https://ux.stackexchange.com/questions/82015/how-do-users-know-to-hover-over-elements
* https://ux.stackexchange.com/questions/13706/how-can-i-make-it-obvious-that-a-page-element-is-to-be-hovered-over

IMO they'd ideally be shown on the desktop all the time, like they are on mobile.

An alternative would be to add some kind of CTA indicator, and then show all titles when any is hovered on.

**Comment by beafialho** [comment]
> Some screens in the mockup have post titles being hidden until the user hovers over them.

Could you point me out to which ones?

**Comment by iandunn** [comment]
Er, my bad, I should have been specific in the issue. I was thinking of the Community category, and the Community section on the homepage

**Comment by beafialho** [comment]
Ah, this one. 

When we designed the "Community" category page, this was something we iterated on and discussed thoughtfully. Ultimately, we thought this could work with the info included on hover if it also appeared when the item is focused (similar to when we're browsing themes on the appearance —> themes page). 

That way people navigating by keyboard would be able to get the title/meta info read out to them when they tab over that item. Doing so while achieving a visual solution (this mosaic view) that metaphorically translates the idea of community.

**Comment by iandunn** [comment]
That makes sense, thanks for elaborating 👍🏻

I don't think a11y will be an issue; I was thinking about how as a sighted user, I'm often frustrated when important info is hidden from me. Hovering over each item is relatively time-consuming and annoying when compared to just scanning my eyes over a page.

In our context, it's also common for me to recognize someone's _name_, but not their _face_.  I'm much more likely to click if I see something I recognize.

I get that it's subjective, though, and I appreciate that you've already spent a lot of time thinking through it.

I think one improvement might be to show _all_ names when _any_ of them are hovered on, but I'm also fine leaving it the way it is if you think that's best.

**Comment by beafialho** [comment]
> I'm often frustrated when important info is hidden from me. Hovering over each item is relatively time-consuming and annoying when compared to just scanning my eyes over a page. In our context, it's also common for me to recognize someone's name, but not their face. I'm much more likely to click if I see something I recognize.

I totally know what you mean, thanks for explaining! 

I'm often frustrated too with some choices, usually overly animated sites that load really slowly/poorly, that impose me a certain time to watch videos or intros... These decisions usually don't please every user, but I think in this particular case we can take that risk in order to highlight the _people_ of the WordPress community 🙂

**Comment by iandunn** [comment]
Sounds good, thanks for discussing it :)
