### ISSUE TITLE
Should post meta contain author avatar?

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-news-2021#56]
The post author block can display the author's avatar. That might help readers feel a bit more connected to the author, rather than just seeing their name.

**Comment by beafialho** [comment]
I think we should keep the post meta without an avatar. In the designs, an avatar in that area would create unbalance, and readers can click the author's name and be taken to the author's profile page. Also, more avatars are shown in the likes section, which contributes to the connection feeling you're referring to.

**Comment by iandunn** [comment]
Sounds good 👍🏻
