### ISSUE TITLE
Implement global header/footer design for News site

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-news-2021#6]
https://www.figma.com/file/O9I8Jl7kaUMTX39LlRGbGO/News-Page?node-id=4659%3A8203

It may be easiest to get it working for News first, and the roll it out to the rest of the network in #7. 

It should take into account any foreseeable needs for the network-wide rollout, though.

- [x] basic styles - mobile
- [x] basic styles - desktop
- [x] header menu
- [x] header search
- [x] overflow menu
- [x] responsive breakpoints
- [x] footer - mobile
- [x] footer - desktop

**Comment by iandunn** [comment]
I was thinking of creating a "global header" dynamic block, and include that in `block-template-parts/header.html` (see https://github.com/WordPress/wporg-news-2021/issues/4#issuecomment-901306142). 

I don't think that's actually necessary, though. That block would contain the entire header area, and I'm assuming we're not going to want users changing the global header/footer. 

So, I think we can just skip FSE for the header/footer area, and treat it like a classic theme. The sidebar/content area would still be FSE, though.

How does that sound @coreymckrill ?

**Comment by coreymckrill** [comment]
If we can get that to work, that's probably fine for now. I still don't have a great understanding at this point of how block templates are loaded, and if you can even mix and match php and html template parts...

**Comment by iandunn** [comment]
Oh, huh, it looks like the `themes/wporg-news-2021/header.php` is never used; maybe Blockbase included it as a fallback or something?

If it's not used, then I think we'll need a header block after all. I'll take a closer look tomorrow.

**Comment by coreymckrill** [comment]
I think it's only used in the 404.php template.

**Comment by iandunn** [comment]
huh, but there's a `404.html` too. 

maybe it's just for translation? https://github.com/Automattic/themes/commit/ae7e63d133020db5df58584c1d019315dc2bc3a3

**Comment by coreymckrill** [comment]
Ah, interesting. Good find.

**Comment by coreymckrill** [comment]
> I was thinking of creating a "global header" dynamic block, and include that in block-template-parts/header.html

Thinking more about this. It does seem like this would be feasible, for both the header and the footer, it could just use a server side render and not have any options or UI. Maybe it would go in a separate plugin, `wporg-site-blocks` or something?

> I'm assuming we're not going to want users changing the global header/footer.

Yeah this seems related to #14. I haven't looked into whether specific templates can be locked (i.e. prevent users from editing them/creating versions stored in the db), but it seems like this should be doable. I suspect at first we'd just want to lock everything down, and then unlock things as the need arises.

**Comment by iandunn** [comment]
rough sketch of that here:

* https://github.com/WordPress/wporg-news-2021/pull/20/
* https://github.com/WordPress/wporg-repo-tools/pull/9

**Comment by coreymckrill** [comment]
Another thought: given the current limitations of FSE, we could have this theme take a hybrid approach: Use a theme.json file, but still use classic PHP-style templates instead of block templates. If we wanted to keep the door open for refactoring to full FSE later, the PHP templates could still include block grammar where feasible, so they'd be easier to convert to block templates in the future...

**Comment by iandunn** [comment]
🤔 , my gut feeling is that'd introduce more technical debt overall, and it'd be better to commit to one or the other.

But then, if we end up having to create faux blocks for a lot of stuff... it might be less awkward to just use the parts of FSE that work for us today, and hold off on the others 🤷🏻‍♂️ 

I don't feel too strongly. Are you leaning one way or the other?

**Comment by coreymckrill** [comment]
I've been vacillating on this. If it turns out that global header and footer are the only things we need "faux" blocks for, maybe we can, in fact, stick with block templates as well. I'm working on #17 right now, and I might have a firm opinion after that.

**Comment by iandunn** [comment]
The foundation for this has been merged in https://github.com/WordPress/wporg-mu-plugins/pull/4 and #20.

I'll work on the actual content next.

**Comment by iandunn** [comment]
@coreymckrill, what was your process for creating the markup in #21? 

I was thinking about using `wp-admin/post-new.php?post_type=wp_template_part`, and then copy/pasting the source into the PHP file. That seems like an awful devex, though, especially when iterating.

Did you come up with something better? 

If not, maybe we could write an mu-plugin that would save wp-admin changes to the PHP file in addition to the db? That'd probably wipe out any PHP comments that we'd want, so we'd have to make them HTML comments, which would be a pain Gutenberg. I guess we could have a delimiter in the PHP file, and only things _after_ it would be overwritten.

**Comment by iandunn** [comment]
hey @beafialho  👋🏻 
did you intend for the footer mockup to have this in the 6th column of links?

```
@WordPress
Wordpress [sic]
```

The current footer has those links, along w/ the Twitter/FB logos to their left. In Figma, the logos are floating in the bottom right, so they don't seem attached to the text, and the link text isn't descriptive enough for users to know what they'd be clicking on. 

Should the text be removed in the new design, or did you want to keep it there and just have the logos in a different location?

**Comment by beafialho** [comment]
Hi @iandunn thanks for pointing that out, I missed that detail!

The intent is to have the social links be the icons at the bottom, so let's remove the last column of links.

<img width="1451" alt="footer" src="https://user-images.githubusercontent.com/65220155/131464342-f93e4bf4-8a30-4cd7-a2d2-881006a0a95f.png">

**Comment by iandunn** [comment]
Sounds good, thanks!

**Comment by iandunn** [comment]
I took the liberty of adding `Mobile` and `Patterns` to the footer, since they're in the header. It doesn't make sense for anything in the header to be missing from the footer IMO.

I also added OpenVerse to the header and footer, since it should launch before this does. We can adjust if that changes though.

**Comment by beafialho** [comment]
Good idea, I see no reason why they shouldn't be there.

**Comment by coreymckrill** [comment]
@iandunn

> what was your process for creating the markup in #21?
>
> I was thinking about using wp-admin/post-new.php?post_type=wp_template_part, and then copy/pasting the source into the PHP file. That seems like an awful devex, though, especially when iterating.
>
> Did you come up with something better?

Nope. I used the block editor a few times and just switched to Code View to copy/paste, but after I had enough sample material in my files, I just started copy/pasting it from there and changing the block names and attributes by hand.

**Comment by iandunn** [comment]
Yeah, that's what I've mostly ended up doing too 👍🏻

**Comment by iandunn** [comment]
@beafialho , in the mockup, the header menu is `1320px` wide; how should it look at a normal desktop size, like the `900-1100px` range?

Should the menu wrap to a 2nd row? If so, what kind of spacing do you want, etc?

**Comment by beafialho** [comment]
@iandunn this should be the behaviour of the header in different screen sizes:

- In the largest screen size, the menu links should stick to the left
- The first element to be hidden should always be the logo (leaving the WP icon only), followed by the "Get WordPress" button
- The menu should collapse at 876px turning into the mobile option

I've added a responsive section to the [Figma file](https://www.figma.com/file/O9I8Jl7kaUMTX39LlRGbGO/News-Page?node-id=7413%3A31041) with all these mockups there.

<img width="925" alt="header" src="https://user-images.githubusercontent.com/65220155/133096127-1b7746b0-b84a-4620-97c7-fb680492ea33.png">

**Comment by iandunn** [comment]
This should be all done, except for pixel perfect tweaks.
