### ISSUE TITLE
Simplify local nav background

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-news-2021#62]
Right now each individual category needs a new image created, but we should be able to just set background colors in CSS instead.

I don't think I can do it with the current SVG in Figma, though, because the paths define the top area, and I need them to define the bottom area.

@beafialho , can you create a SVG that is the _inverse/opposite_ of those 2 stroke vectors?

So, in the image below, instead of the top area being filled with blue and bottom area transparent, the top area would be transparent and the bottom would be filled white.

![inverse-example](https://user-images.githubusercontent.com/484068/139347490-c4206254-ee05-4f5c-a7da-d5c40eb1e19f.png)

_( ignore the fact that the hue of blue is different than the mockup, that was just for an example. i'll make the actual background colors match the mockup )_

**Comment by iandunn** [comment]
Nevermind @beafialho , I figured out how to do it w/ `mask-image` in CSS 🙂

**Comment by beafialho** [comment]
Awesome!
