### ISSUE TITLE
Group event posts by year

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-news-2021#74]
The mockup has the posts grouped by year, with the year showing up in the left column. 

That wasn't implemented in #65, since it's tricky to do without [dynamic templates](https://github.com/WordPress/gutenberg/issues/32939), and not essential for the launch.

This is interrelated with #75

**Comment by ryelle** [comment]
This is a duplicate of #281, which has the mockup screenshot & some discussion. Closing in favor of that issue.
