### ISSUE TITLE
Fix pagination number `found_posts`

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-news-2021#80]
After 483f34db1518a6f09f203f3c5f953de0c245c1e8, the `wp:query-pagination-numbers` block shows 10 pages when it should show 11.

I think the problem is the one described at https://codex.wordpress.org/Making_Custom_Queries_using_Offset_and_Pagination#Offset_Using_pre_get_posts, where `found_posts` needs to be adjusted to account for the new `offset`.

```php
add_filter( 'found_posts', __NAMESPACE__ . '\foo', 1, 2 );
function foo( $found_posts, $query ) {
	$is_posts_index = is_posts_index( $query );
	
	if ( ! $is_posts_index ) {
		return $found_posts;
	}
	
	return $found_posts + 5;
}
```

This is blocked by #70 , though.

**Comment by coreymckrill** [comment]
#70 is closed now. Is this still blocked @iandunn?

**Comment by iandunn** [comment]
No, but it looks like the problem was also fixed by some earlier change 👍🏻
