### ISSUE TITLE
Refine background for `query-pagination` block

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-news-2021#84]
`query-pagination` has the same problem/needs as #67 . Once a solution is found there, it should be applied to this block too.

**Comment by iandunn** [comment]
@MaggieCabrera , do you think your gradient technique in #67 will work here too? There are several places where the bg color of `wp-block-query-pagination` needs to change based on the context. e.g., "See All Releases" on the front page.

**Comment by MaggieCabrera** [comment]
> @MaggieCabrera , do you think your gradient technique in #67 will work here too? There are several places where the bg color of `wp-block-query-pagination` needs to change based on the context. e.g., "See All Releases" on the front page.

@iandunn I'm not sure if it's the same issue, I'm looking at the mockups, and the stroke over "See all releases" looks different than what's on the test site in terms of color and shape. I also see a stroke under News that isn't there. but I think we can do something about it anyway.

Just to clarify, what we need to have is what's on the mockup for the paginations that have a darker background while maintaining what's already working for the ones under a white background, yes?

**Comment by MaggieCabrera** [comment]
Ok I see what you mean when you are comparing this to #67 and yes, using ::after here also makes it much easier to style, I'm going to open a PR for this and we work from there
