### ISSUE TITLE
production category IDs don't match local env

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-news-2021#85]
currently you have to manually update `term_id` in your local `wp_terms` and `wp_term_taxonomy` for the front page templates to work, b/c the have the production IDs hardcoded

the WRX from #10 doesn't have include category IDs because [we exported specific post types rather than "all content"](https://wordpress.stackexchange.com/questions/34759/how-to-export-and-import-taxonomies-category-tag-and-or-custom-taxonomy-and-t)

we could update our export/import process to use "all content", but remove stuff we don't want later on. we'd probably have to hack together something that applies `can_export => false` to all the post types we don't want, though.

- [ ] generate new export file w/ all content, limit to `publish` post status
- [ ] ⚠️ prune for privacy 
- [ ] remove old files
- [ ] update docs for export process

Alternatively, we could query by category slug if https://github.com/WordPress/gutenberg/issues/36785 if resolved

**Comment by tellyworth** [comment]
What do you think of the idea of creating a custom `wporg:query` block that extends the core `wp:query` block, and adds support for querying by category slug (and anything else we need)?

It could essentially just do a slug -> id lookup and then wrap the core block. Though I'm not sure how easy that is, given that it's a JS block not dynamic.

**Comment by iandunn** [comment]
🤔 , I think that'd work, and it sounds like a good solution. Definitely worth exploring 👍🏻

**Comment by ryelle** [comment]
I'm going to close this because the `custom_query_block_attributes` workaround enables the query block to accept category and tag slugs now (and removing the workaround is tracked in #79).
