### ISSUE TITLE
Global & Local Nav Bars visual refinements

### ISSUE THREAD

**Issue by beafialho** [WordPress/wporg-news-2021#86]
Here are a few visual enhancements we can make to these bars:

- [x] Arrows in Global Nav Bar should match with Local Nav Bar's
- [x] The active menu link (News in this case) should be **bold** and highlighted through color `#7B90FF`
- [x] The "Get WordPress" button should have a `2px` border radius and its text should be **bold**

Currently:
<img width="1532" alt="Captura de ecrã 2021-11-24, às 11 59 15" src="https://user-images.githubusercontent.com/65220155/143234563-ef3cd4a4-f66f-47e4-b679-7bb2476236a0.png">

Intended:
<img width="1510" alt="Captura de ecrã 2021-11-24, às 12 01 12" src="https://user-images.githubusercontent.com/65220155/143234761-424ab656-c81c-49a0-8730-5c68b11dd16a.png">

- [x] Search icon should be centered to its container:
<img width="894" alt="Captura de ecrã 2021-11-24, às 12 08 58" src="https://user-images.githubusercontent.com/65220155/143235844-8f8da6c1-ddd7-4365-a320-6458d009f947.png">

- [x] The header responsiveness isn't ideal at the moment, because the links jump straight into the smallest version of the `…` nav, when they should go in there gradually. Here's what we could use to improve that: https://css-tricks.com/the-priority-navigation-pattern/

https://user-images.githubusercontent.com/65220155/143241364-b16c4b3e-0dd2-45bf-9969-46adba150a48.mp4

**On mobile:**

- [x] Let's decrease the text size of the submenu items
- [x] "Close" icon should be inside its container
- [x] "Close" section and the menu's background should be a darker shade specified in Figma `#1C2024`

<img width="884" alt="Captura de ecrã 2021-11-24, às 12 52 34" src="https://user-images.githubusercontent.com/65220155/143242066-5bec6c91-83cd-4042-a8ca-3274d230c82c.png">

**Comment by tellyworth** [comment]
@jeffikus or @kellychoffman is this something your teams could help with?

**Comment by kellychoffman** [comment]
If someone can implement, we can review.

**Comment by MaggieCabrera** [comment]
Working on this over at https://github.com/WordPress/wporg-mu-plugins/pull/20

**Comment by MaggieCabrera** [comment]
I've done everything in the linked PR above except the item about the responsive menu with the `...`. I don't think we can do much about it without some heavy handed JS, is that something we want to do?

**Comment by dd32** [comment]
> responsive menu with the `...`. I don't think we can do much about it without some heavy handed JS

I think this is something worth splitting into a separate PR for visibility and implementation.

To me it feels like the user experience would be worth the potentially heavy JS, even though for most users it would only ever be run once (upon load, as they wouldn't usually be resizing the window often).

It would make it easier to bring it to localised sites too, where translations of menu items can be much longer than the English counterparts.

**Comment by MaggieCabrera** [comment]
> I think this is something worth splitting into a separate PR for visibility and implementation.

Perfect then https://github.com/WordPress/wporg-mu-plugins/pull/20 is ready for review for the rest of the issues 
 
> It would make it easier to bring it to localised sites too, where translations of menu items can be much longer than the English counterparts.

+1 I agree, I just wanted to make sure this is what we wanted to do

**Comment by MaggieCabrera** [comment]
The menu script is over here: https://github.com/WordPress/wporg-mu-plugins/pull/21

**Comment by mikachan** [comment]
Hi all. Just checking if there is any remaining work to do from this issue, as it looks like @MaggieCabrera has finished the two remaining tasks:

- 'Search icon should be centered to its container' was fixed in https://github.com/WordPress/wporg-mu-plugins/pull/20
- The header responsiveness was addressed in https://github.com/WordPress/wporg-mu-plugins/pull/21

Is there anything else from the above that needs to be worked on or reviewed?

**Comment by kellychoffman** [comment]
Ah, I didn't see those PRs. Would be good to mark a designer as a reviewer in the future. 

For now: Can we see the changes in https://github.com/WordPress/wporg-mu-plugins/pull/20? Via a screenshot. Or possibly update the test site? Whatever is easiest.

**Comment by mikachan** [comment]
Yep OK, we'll make sure we add a designer as a reviewer in the future 👍

Yes, sure - here are some screenshots from https://github.com/WordPress/wporg-mu-plugins/pull/20:

Search icon centered to its container at large resolutions:
![image](https://user-images.githubusercontent.com/1645628/145019070-ec3a4c60-37c5-4beb-b916-177220664606.png)

Here's a screenshot that shows the arrows, active menu link, and Get WordPress button updates:
![image](https://user-images.githubusercontent.com/1645628/145019147-d9b53f99-7df2-42fa-8795-52e9d6b49be1.png)

I've just noticed a few other bugs with the search icon at smaller resolutions, so I'll open up a PR for them as soon as I can.

**Comment by mikachan** [comment]
Yep OK, we'll add a designer as a reviewer in the future 👍

Yes sure - here is a screenshot of the changes from https://github.com/WordPress/wporg-mu-plugins/pull/20:

![image](https://user-images.githubusercontent.com/1645628/145066844-30d0d57b-068a-42da-8179-467568b88def.png)

**Comment by mikachan** [comment]
Here's a PR for the search improvements: https://github.com/WordPress/wporg-mu-plugins/pull/25
