### ISSUE TITLE
single post

### ISSUE THREAD

**Issue by tellyworth** [WordPress/wporg-news-2021#97]
Hide likes/sharing if #24 isn't done in time.

**Comment by tellyworth** [comment]
#24 is looking promising: https://github.com/WordPress/wporg-news-2021/issues/24#issuecomment-984270021

**Comment by tellyworth** [comment]
#99 seems to have fixed the Likes button.

Design folks: there are still some issues with the appearance of likes and sharing buttons. Can we get a call as to whether or not it looks acceptable for a SotW demo? cc @kellychoffman @beafialho.

**Comment by kellychoffman** [comment]
Do you have an updated screenshot? I don't believe the test site is reflecting the latest changes.

**Comment by tellyworth** [comment]
I think the test site is showing the latest changes for the sharing and like buttons, which is to say default styling:
<img width="370" alt="Screen Shot 2021-12-06 at 3 13 05 pm" src="https://user-images.githubusercontent.com/7200686/144786122-b94ed5b7-ec8d-44b4-ba04-6a48a6a41b68.png">

In my limited understanding we could style the sharing buttons, but not the Like button because it's an iframe. Is there a well-known method for doing that? @dd32 any ideas?

**Comment by dd32** [comment]
> In my limited understanding we could style the sharing buttons, but not the Like button because it's an iframe. Is there a well-known method for doing that?

After tracking down the section in figma, As far as I know, Jetpack likes can't be used in the manner suggested in the designs.

There are ways to customise some of the iframe internals, but I'm not sure if this is still up-to-date: https://cfinke.wordpress.com/2013/04/18/customize-jetpack-like/ 

![image](https://user-images.githubusercontent.com/767313/144796811-0bf88277-edb4-427a-8ae8-1fe7bdbadc80.png)
![image](https://user-images.githubusercontent.com/767313/144797839-7bce8894-f8bb-4a0c-9a1f-6e64a30d94d6.png)


A custom block / custom open-source likes using w.org accounts could do that design though I'm sure..

**Comment by tellyworth** [comment]
Huh, nice find (@cfinke's post). I think for SotW we're best to just hide both of them.

**Comment by dd32** [comment]
>  I think for SotW we're best to just hide both of them.

I agree, so I've disabled those [Jetpack Features on this page](https://wordpress.org/news-test/wp-admin/admin.php?page=jetpack#/sharing)

**Comment by tellyworth** [comment]
Counting this as fixed for SotW.
