### ISSUE TITLE
Choose a post for SotW demo, and make sure all styling is complete

### ISSUE THREAD

**Issue by tellyworth** [WordPress/wporg-news-2021#98]
Ideally we want a post (or two?) for the SotW demo that is visually appealing and shows off a range of different types of blocks and content.

https://wordpress.org/news-test/2021/07/20/tatum/ for example, though something fresher would be best. I'd suggest:

- [x] Choose two or three visually interesting News blog posts that we can show off in the demo, with a range of blocks and a variety of content.
- [x] Test each of those posts very carefully, and open issues for any visible glitches
- [x] Confirm a list of 2-3 posts that work perfectly, to be used in the demo
- [x] Also document and mark as private any posts that should not be used because of unfixed issues!

**Comment by jeffikus** [comment]
@tellyworth - has anyone started work on choosing the blog posts for this? We don't have as full a context as you do for that, so I think it would be better that those posts come from you.

**Comment by tellyworth** [comment]
I don't think so. I'll pick a few to begin with. Let's see if the design folks can help us narrow this down to 2 or 3 for the demo:

https://wordpress.org/news-test/2021/05/10/people-of-wordpress-fike-komala/
https://wordpress.org/news-test/2021/12/08/wordpress-5-9-beta-2/
https://wordpress.org/news-test/2021/12/08/the-month-in-wordpress-november-2021/
https://wordpress.org/news-test/2021/12/08/watch-state-of-the-word-at-a-watch-party-with-your-wordpress-friends/
https://wordpress.org/news-test/2021/07/20/tatum/

**Comment by tellyworth** [comment]
@kellychoffman can someone from Design help with the decisions here?

**Comment by beafialho** [comment]
Here are some posts I suggest:

https://wordpress.org/news-test/2021/05/10/people-of-wordpress-fike-komala/
https://wordpress.org/news-test/2021/12/08/upcoming-gallery-block-improvements/
https://wordpress.org/news-test/2021/12/08/people-of-wordpress-devin-maeztri/

**Comment by matiasbenedetto** [comment]
I created an issue for a particular problem I found: https://github.com/WordPress/wporg-news-2021/issues/117

**Comment by tellyworth** [comment]
#117 is fixed, so I think we can consider the tasks here complete.
